#!/usr/bin/env python3
# Lemmings In-Game Level Editor V2.0
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Assemble the editor sources in src/ and embed the result in patch.py.

Usage: python3 build.py [--vasm PATH]

Requires the vasm 68000 assembler with Motorola syntax (vasmm68k_mot). The
editor is built twice: for floppy, and with WHDLOAD defined for the WHDLoad
install (whdload/src replaces the floppy disk code). Each editor image is
packed in the format of the game's own unpacker as the file Editor, which
patch.py stores behind the boot loader of disk 1. The WHDLoad slave and the
install's icon are built by whdload/build.py. Only the section of patch.py between the "GENERATED BY
build.py" markers is rewritten, so users of patch.py need only Python 3.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import importlib.util
import re
import shutil
import struct
import subprocess
import tempfile
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PATCH = ROOT / 'patch.py'
VERSION = '2.0'
BEGIN = '# BEGIN GENERATED BY build.py - do not edit by hand\n'
END = '# END GENERATED BY build.py\n'

# Must match patch.py: the bootstrap is appended to the game program at
# $21B4C and must end before the editor's chip-memory status bitmap.
CODE_BASE = 0x400
BOOTSTRAP_BASE = 0x21B4C


def assemble(vasm: str, name: str, work: Path,
             defines: dict[str, int] | None = None) -> tuple[bytes, dict[str, int], Path]:
    binary, listing = work / f'{name}.bin', work / f'{name}.lst'
    options = [f'-D{key}={value}' for key, value in (defines or {}).items()]
    if 'WHDLOAD' in (defines or {}):
        options += ['-I', str(ROOT / 'whdload/src')]
    subprocess.run([vasm, '-m68000', '-Fbin', '-quiet', '-L', str(listing),
                    '-I', str(ROOT / 'src'), *options, '-o', str(binary),
                    str(ROOT / 'src' / f'{name}.s')], check=True)
    symbols = {symbol: int(value, 16) for symbol, value in re.findall(
        r'^(\w+)\s+[AE]:([0-9A-Fa-f]+)(?: EXP)?$', listing.read_text(), re.M)}
    return binary.read_bytes(), symbols, listing


def check_absolute_operands(listing: Path) -> None:
    """Refuse game addresses that the assembler turned into PC-relative operands.

    The editor is assembled at 0 but runs in slow RAM. vasm may encode an
    absolute operand such as $8cd6 as d16(PC) when it is within reach of the
    assembly address, which points into the editor at run time. Game addresses
    are therefore written as (addr).l. For the same reason a jmp or jsr to one
    of the editor's own labels would go to its assembly address; the sources
    use bra or bsr.
    """
    for line in listing.read_text().splitlines():
        match = re.match(r'^\w+:([0-9A-F]+) ([0-9A-F]{4})[0-9A-F]*\s+\d+:\s*(?:[\w.]+:)?\s*(\S+)\s+([^;]*)', line)
        if not match:
            continue
        mnemonic, operands = match[3].lower(), match[4].lower()
        if mnemonic.startswith(('b', 'db', 'dc', 'even', 'include')):
            continue
        source = operands.split(',')[0]
        if mnemonic in ('jmp', 'jsr') and re.match(r'[a-z_.]', source) and '(' not in source:
            raise ValueError(f'jump to an editor label by absolute address: {line.strip()}')
        if source.startswith('#') or mnemonic.startswith('moveq'):
            continue                    # the low bits hold data, not an address mode
        if int(match[2], 16) & 0x3f == 0x3a and '(pc)' not in source:
            raise ValueError(f'absolute operand became PC-relative: {line.strip()}')


def check_layout(es: dict[str, int], bs: dict[str, int], editor: bytes, bootstrap: bytes) -> None:
    """Check the memory layout of the reserved slow-RAM block and the bootstrap."""
    if (es['image_end'] != len(editor) or es['state'] != len(editor)
            or es['storage_end'] > min(es['GFX'], bs['PACKED_OFFSET'])
            or es['DISK_WORK'] < es['GFX'] + es['GFX_MAX_BYTES']
            or es['DISK_TRACK'] != es['DISK_WORK']
            or es['DISK_VERIFY'] != es['DISK_TRACK'] + es['TRACK_BYTES']
            or es['DISK_HEADER'] != es['DISK_VERIFY'] + es['TRACK_BYTES']
            or es['DISK_WORK_END'] != es['DISK_HEADER'] + es['TRACK_BYTES']
            or es['DISK_WORK_END'] > es['EDITOR_RESERVE']
            or es['EDITOR_RESERVE'] != 0x20000
            or bs['reserve'] != BOOTSTRAP_BASE
            or BOOTSTRAP_BASE + len(bootstrap) > es['CHIP_TEXT']):
        raise ValueError('editor or bootstrap exceeds its reserved memory')


def pack(data: bytes) -> bytes:
    """Pack data for the game's unpacker ($3934).

    The stream is decoded backwards, from the end of the file to its start, and
    written from the end of the output buffer. This encoder is a greedy LZ with
    distances up to 4095 bytes and matches up to 256 bytes. The last stream word
    carries a sentinel bit; the trailer holds the XOR of all stream words and
    the unpacked length.
    """
    if not 0 < len(data) <= 0x80000:
        raise ValueError('resource size must be in 1..524288')
    source = data[::-1]
    bits: list[int] = []

    def emit(value: int, width: int) -> None:
        bits.extend((value >> shift) & 1 for shift in range(width - 1, -1, -1))

    def literals(start: int, end: int) -> None:
        while start < end:
            count = min(264, end - start)
            if count <= 8:
                emit(0, 2)
                emit(count - 1, 3)
            else:
                emit(7, 3)
                emit(count - 9, 8)
            for value in source[start:start + count]:
                emit(value, 8)
            start += count

    pos = pending = 0
    while pos < len(source):
        best = (0, 0, 0)
        # Try every earlier occurrence of the next two bytes (overlapping copies
        # included) and keep the greatest bit saving; shorter distances win ties.
        candidate = source.rfind(source[pos:pos + 2], max(0, pos - 4095), pos + 1)
        while 0 <= candidate < pos and pos + 1 < len(source):
            distance = pos - candidate
            count = 2
            while count < min(256, len(source) - pos) and source[candidate + count] == source[pos + count]:
                count += 1
            options = [(2, 10)] if distance < 256 else []
            if count >= 3 and distance < 512:
                options.append((3, 12))
            if count >= 4 and distance < 1024:
                options.append((4, 13))
            if count >= 3:
                options.append((count, 23))
            for length, cost in options:
                saving = length * 8 - cost
                if saving > best[0]:
                    best = (saving, length, distance)
            if count == 256:
                break
            candidate = source.rfind(source[pos:pos + 2], max(0, pos - 4095), candidate + 1)
        if best[0] <= 0:
            pos += 1
            continue
        literals(pending, pos)
        _, count, distance = best
        if count == 2:
            emit(1, 2)
            emit(distance, 8)
        elif count == 3 and distance < 512:
            emit(4, 3)
            emit(distance, 9)
        elif count == 4 and distance < 1024:
            emit(5, 3)
            emit(distance, 10)
        else:
            emit(6, 3)
            emit(count - 1, 8)
            emit(distance, 12)
        pos += count
        pending = pos
    literals(pending, pos)
    first = min(31, len(bits))
    words = [(1 << first) | sum(bit << i for i, bit in enumerate(bits[:first]))]
    for offset in range(first, len(bits), 32):
        words.append(sum(bit << i for i, bit in enumerate(bits[offset:offset + 32])))
    checksum = 0
    for word in words:
        checksum ^= word
    return (b''.join(struct.pack('>I', word) for word in reversed(words))
            + struct.pack('>II', checksum, len(data)))


def unpack(data: bytes) -> bytes:
    """Python model of the game's unpacker ($3934), used to check pack()."""
    if len(data) < 12 or len(data) % 4:
        raise ValueError('invalid packed size')
    size = int.from_bytes(data[-4:], 'big')
    if not 0 < size <= 0x80000:
        raise ValueError('invalid unpacked size')
    source = len(data) - 12
    bits = int.from_bytes(data[source:source + 4], 'big')
    checksum = int.from_bytes(data[-8:-4], 'big') ^ bits
    output = bytearray(size)
    pos = size

    def bit() -> int:
        nonlocal bits, source, checksum
        value = bits & 1
        bits >>= 1
        if bits == 0:
            source -= 4
            if source < 0:
                raise ValueError('packed stream exhausted')
            word = int.from_bytes(data[source:source + 4], 'big')
            checksum ^= word
            value = word & 1
            bits = 0x80000000 | (word >> 1)
        return value

    def read(count: int) -> int:
        value = 0
        for _ in range(count):
            value = (value << 1) | bit()
        return value

    while pos:
        literal = False
        if bit() == 0:
            if bit() == 0:
                count, literal = read(3) + 1, True
            else:
                count, distance = 2, read(8)
        else:
            kind = read(2)
            if kind == 3:
                count, literal = read(8) + 9, True
            elif kind == 2:
                count, distance = read(8) + 1, read(12)
            else:
                count, distance = kind + 3, read(kind + 9)
        if count > pos:
            raise ValueError('output underflow')
        for _ in range(count):
            pos -= 1
            if literal:
                output[pos] = read(8)
            else:
                if distance <= 0 or pos + distance >= size:
                    raise ValueError('invalid back-reference')
                output[pos] = output[pos + distance]
    if checksum:
        raise ValueError('checksum mismatch')
    return bytes(output)


def encode(data: bytes) -> str:
    """A base64 string literal split over lines of at most 79 characters."""
    lines = textwrap.wrap(base64.b64encode(data).decode('ascii'), 68)
    return '(\n' + ''.join(f"        '{line}'\n" for line in lines) + '    )'


def editor_variant(vasm: str, defines: dict[str, int]) -> tuple[dict, dict[str, bytes], str]:
    """Assemble, check and pack one editor build and its bootstrap."""
    with tempfile.TemporaryDirectory() as directory:
        work = Path(directory)
        editor, es, listing = assemble(vasm, 'editor', work, defines)
        check_absolute_operands(listing)
        bootstrap, bs, _ = assemble(vasm, 'bootstrap', work)
    check_layout(es, bs, editor, bootstrap)
    packed = pack(editor)
    try:
        valid = unpack(packed) == editor
    except ValueError:
        valid = False
    # The packed file is loaded to the staging area inside the reserved block.
    if not valid or bs['PACKED_OFFSET'] + len(packed) > es['EDITOR_RESERVE']:
        raise ValueError('packed editor fails its round trip or does not fit')
    blobs = {'bootstrap': bootstrap, 'Editor': packed}
    symbols = {'reserve': bs['reserve'], 'load_editor': bs['load_editor'],
               'install_editor': bs['install_editor'], 'limit': es['CHIP_TEXT']}
    summary = (f'editor image {len(editor)} bytes ({es["storage_end"]} with storage), '
               f'Editor {len(packed)} packed bytes')
    return symbols, blobs, summary


def build(vasm: str) -> tuple[str, str]:
    spec = importlib.util.spec_from_file_location('whdload_build', ROOT / 'whdload/build.py')
    whdload = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(whdload)
    variants, blobs, summaries = {}, {}, []
    for variant, defines in (('floppy', {}), ('whdload', {'WHDLOAD': 1})):
        symbols, parts, summary = editor_variant(vasm, defines)
        variants[variant] = symbols
        blobs.update({f'{variant} {name}': data for name, data in parts.items()})
        summaries.append(f'{variant}: {summary}')
    # The slave accepts only its own disk images: the patched Code file (the
    # original program $400..$21B4B plus the bootstrap) and Editor must have
    # the lengths of the WHDLoad build.
    code_size = BOOTSTRAP_BASE - CODE_BASE + len(blobs['whdload bootstrap'])
    blobs['Lemmings.slave'] = whdload.slave(vasm, code_size, len(blobs['whdload Editor']))
    blobs['Lemmings.info'] = whdload.icon()
    generated = (
        f"VERSION = '{VERSION}'\n"
        'VARIANTS = {\n'
        + ''.join(f"    '{name}': {{" + ', '.join(f"'{k}': 0x{v:X}" for k, v in symbols.items())
                  + '},\n' for name, symbols in variants.items())
        + '}\n'
        'SHA256 = {\n'
        + ''.join(f"    '{name}': '{hashlib.sha256(data).hexdigest()}',\n"
                  for name, data in blobs.items())
        + '}\n'
        'BLOBS = {\n'
        + ''.join(f"    '{name}': {encode(data)},\n" for name, data in blobs.items())
        + '}\n')
    summary = f'V{VERSION}; ' + '; '.join(summaries) + f'; slave {len(blobs["Lemmings.slave"])} bytes'
    return generated, summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--vasm', default='vasmm68k_mot',
                        help='path or name of the vasm 68000 assembler')
    args = parser.parse_args()
    vasm = shutil.which(args.vasm)
    if not vasm:
        parser.exit(1, f'error: assembler not found: {args.vasm}\n')
    try:
        generated, summary = build(vasm)
    except subprocess.CalledProcessError as error:
        parser.exit(1, f'error: assembly failed: {error}\n')
    except ValueError as error:
        parser.exit(1, f'error: {error}\n')
    text = PATCH.read_text()
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        parser.exit(1, 'error: generated-section markers not found in patch.py\n')
    head, rest = text.split(BEGIN)
    _, tail = rest.split(END)
    PATCH.write_text(head + BEGIN + generated + END + tail)
    print(f'patch.py updated: {summary}')


if __name__ == '__main__':
    main()
