#!/usr/bin/env python3
# Lemmings In-Game Level Editor V1.0
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Assemble the editor sources in src/ and embed the result in patch.py.

Usage: python3 build.py [--vasm PATH]

Requires the vasm 68000 assembler with Motorola syntax (vasmm68k_mot). Only the
section of patch.py between the "GENERATED BY build.py" markers is rewritten,
so users of patch.py need only Python 3.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import re
import shutil
import subprocess
import tempfile
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PATCH = ROOT / 'patch.py'
VERSION = '1.0'
BEGIN = '# BEGIN GENERATED BY build.py - do not edit by hand\n'
END = '# END GENERATED BY build.py\n'

# Must match the limits in patch.py.
BOOTSTRAP_BASE = 0x21B4C
BOOTSTRAP_LIMIT = 0x21C00
EDITOR_LIMIT = 0x4000


def assemble(vasm: str, source: Path, work: Path) -> tuple[bytes, dict[str, int]]:
    binary, listing = work / f'{source.stem}.bin', work / f'{source.stem}.lst'
    subprocess.run([vasm, '-m68000', '-Fbin', '-quiet', '-L', str(listing),
                    '-o', str(binary), str(source)], check=True)
    symbols = {name: int(value, 16) for name, value in re.findall(
        r'^(\w+)\s+A:([0-9A-Fa-f]+)$', listing.read_text(), re.M)}
    return binary.read_bytes(), symbols


def encode(name: str, data: bytes) -> str:
    """A base64 string literal split over lines of at most 79 characters."""
    lines = textwrap.wrap(base64.b64encode(data).decode('ascii'), 72)
    return f'{name} = (\n' + ''.join(f"    '{line}'\n" for line in lines) + ')\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--vasm', default='vasmm68k_mot',
                        help='path or name of the vasm 68000 assembler')
    args = parser.parse_args()
    vasm = shutil.which(args.vasm)
    if not vasm:
        parser.exit(1, f'error: assembler not found: {args.vasm}\n')
    with tempfile.TemporaryDirectory() as work:
        try:
            bootstrap, symbols = assemble(vasm, ROOT / 'src/bootstrap.s', Path(work))
            editor, _ = assemble(vasm, ROOT / 'src/editor.s', Path(work))
        except subprocess.CalledProcessError as error:
            parser.exit(1, f'error: assembly failed: {error}\n')
    if symbols.get('reserve') != BOOTSTRAP_BASE:
        parser.exit(1, 'error: bootstrap must start with "reserve" at $21B4C\n')
    if BOOTSTRAP_BASE + len(bootstrap) > BOOTSTRAP_LIMIT:
        parser.exit(1, f'error: bootstrap is {len(bootstrap)} bytes, too large\n')
    if len(editor) >= EDITOR_LIMIT:
        parser.exit(1, f'error: editor is {len(editor)} bytes, limit {EDITOR_LIMIT}\n')

    generated = (
        f"VERSION = '{VERSION}'\n"
        f"BOOTSTRAP_RESERVE = 0x{symbols['reserve']:X}\n"
        f"BOOTSTRAP_LOAD_EDITOR = 0x{symbols['load_editor']:X}\n"
        f"BOOTSTRAP_SHA256 = '{hashlib.sha256(bootstrap).hexdigest()}'\n"
        f"EDITOR_SHA256 = '{hashlib.sha256(editor).hexdigest()}'\n"
        + encode('BOOTSTRAP', bootstrap) + encode('EDITOR', editor))
    text = PATCH.read_text()
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        parser.exit(1, 'error: generated-section markers not found in patch.py\n')
    head, rest = text.split(BEGIN)
    _, tail = rest.split(END)
    PATCH.write_text(head + BEGIN + generated + END + tail)
    print(f'patch.py updated: V{VERSION}, bootstrap {len(bootstrap)} bytes, '
          f'editor {len(editor)} bytes')


if __name__ == '__main__':
    main()
