#!/usr/bin/env python3
# Lemmings In-Game Level Editor V1.1
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Patch Amiga Lemmings disk images with the in-game level editor.

Usage: python3 patch.py DISK1.adf DISK2.adf [-o OUTPUT_DIR]

The two input images may be given in any order; they are identified by their
SHA-256 hashes. Only the exact supported pair is accepted. The inputs are never
modified. Two new images are written to the output directory (default: the
current directory):

    Lemmings_Disk1-editor-patch.adf
    Lemmings_Disk2-editor-patch.adf

Requires only Python 3. The editor code is embedded below; it is generated from
the assembler sources in src/ by build.py.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import re
import struct
import sys
import tempfile
from pathlib import Path

# The supported Lemmings disk images, identified by their SHA-256 hashes.
DISK_SIZE = 901120
INPUT_SHA256 = {
    1: 'a4fdba69017f1a760bba3bb06c55f7e434226c498c9d22c1f627212b08d24f91',
    2: '1526000b96d196efecab9c63aa72c0ce6257649a4993141b00ead8738fd97a65',
}
OUTPUT_NAMES = {n: f'Lemmings_Disk{n}-editor-patch.adf' for n in (1, 2)}

# The game's own disk directory: 16-byte records at $400..$13FF (the first one
# is reserved), each a 12-byte name and a big-endian 32-bit length. File data
# starts at $1600 and is stored back to back in directory order.
DIRECTORY = 0x400
FIRST_RECORD = 0x410
DIRECTORY_END = 0x1400
PAYLOAD = 0x1600
# Disk 1 keeps its raw boot loader at $CA000; files must end before it.
DISK1_PAYLOAD_LIMIT = 0xCA000

# The main program file "Code" loads at $400. The bootstrap is appended to it
# and must end before BOOTSTRAP_LIMIT, where the editor's chip-memory status
# bitmap starts.
CODE_BASE = 0x400
BOOTSTRAP_BASE = 0x21B4C

# BEGIN GENERATED BY build.py - do not edit by hand
VERSION = '1.1'
BOOTSTRAP_RESERVE = 0x21B4C
BOOTSTRAP_LOAD_EDITOR2 = 0x21B68
BOOTSTRAP_LOAD_EDITOR = 0x21BD6
BOOTSTRAP_LIMIT = 0x21D00
BOOTSTRAP_SHA256 = 'e5f08a89a4afaf445223eb4ecf8889fd01a14ede518ff483a7e7c025d184f42c'
EDITOR_SHA256 = '6515d26ed63c71b3e3498366ba7622bc6e0a0f086b2881fff653ec32d30c20db'
EDITOR2_SHA256 = 'a580d3eeb7188ddd90c949578c2da3741f4a984d05ac77e5e45c88c62a16412f'
BOOTSTRAP = (
    '0/gACAy4AAJAAAAIZQaT/AACAAArSQD4Tvg5Hkjn//hB+gC7ShBmVAy4AAJAAAAIZUpB+swi'
    'Q/kABYgAcP9yBSQ8bWFpbk64f7JKgGYuQfoAhSJtAPhD6XAAcgBOuH+ySoBmGCJtAPhB6XAA'
    'Q+kluiABTrg5NEH6AGVQ0EzfH/9OuDxuSkBO+AUQTrg9SAy4AAJAAAAIZS5B+gBDShBnJkH6'
    'ACwibQD4Q+lwAHIATrgyhiJtAPhB6XAAIAFOuDk0IG0A+E6QTrgsfk74BVBFZGl0b3IARWRp'
    'dG9yMgAA'
)
EDITOR = (
    'AAAWgwMvBDJDTWHQhDWGkqJI/Fn4BigRAcoJAAJgEFSACXQFQBC9DlCIEBYBKgDBegagVUg4'
    'wKKAXYFAtUZAoKVRkCgq0AUFIAKCgxkBQoDGQFCsICiJoouQmgUF5EaBQXkFoDFQLEIJsCjR'
    'afAbAIwWnwGwOMFScCKCcJjhT6FaNAKnIDt5MG4KnYDHReJQG2ioAUooGGAUMj4ntCKEBH4D'
    'QgHsmFcRAJEAJqDVQjaCFIRqAI1IO9AYAzQSLAMoKfwCCygkGSxoATv+GwWTKAeIWmLZBtAV'
    'BL8ghYSOoG+CQIzEF4JqMiID8ogFAU4AgYSYwgiC+BEQSBIAhZThZAX6H9H0QGFcyQpCxA6T'
    'JKAoIXACGkq+gOmV5xBPaA2oApOgAcRABGlAxRkgE3IrbCFkkBhN6MMEgQ7mMEHEnTMHQLxj'
    'gZWQCleoNsgWBnrD3ay1BIGEZoJBQoDcVIESAkCKMxghf7MARSQGvQM2QcLhmYQgqTUUGFIG'
    'AuQDCSgGBTgBhbwoDYMqARVgMEIYGQHiMyghKFgUDRBpD1kH8ICbY3gINV0LUCXKBujfAIvA'
    'ZdeAFiYB5lCBV+A5g+gIyFTBtBgmqSBAQLQiLM0B2AiYB5niBYOSBVFoAwQQuAxBgBkgUg6x'
    'oMC54YFwAB8AYBZgjgAQkC0WPECAUIAxUTF9g4kRuE2A3FQbwGECsgTrIGYsgMQGUAICoqUE'
    'KtGaCWyA2IogKsgO2AwTxHxV/6hoU7CFpAaeAYElBgrYNiU0VRwL4AgHkAJugMUAgS+gw4GM'
    'BGyUZmF0ABFEgGDgVSAoCrKEBysBxZtAoEPAX0QNgGmUAlC3aA3d8BgxvBRGmJAYc6A5xS4E'
    'KgjUqhSAQEBALGBFEnAxJQMEKwXMEQBBoAAkfzEAklSKJeIMDDTRDBcy5MAWM6c8QGmAAoEG'
    'KKUAyeZEhkWkjgBygFS4AgFIgNGAxvgN9fAaUBOgwKN0CE7awNsZipBhExQyRrQGJAaooGEz'
    'BUzwYG2DeYKmLICM0QYHAygkBggH/0Bo4MkIMJUmYYgkRQMNNoNEzGECQFBsQBCXSgA5AQlU'
    'oAuTk9gtKAHkDAoQHA2Or7VCAHz4Amk6DgBBDOBYDZmiCn8aSIDYzAZQ7mQMQSgINwYDTB8F'
    'AQYAUiAwg0BmsZFOiwG+3QMJQgM++P+j81QKCAEBsqBgJ9Chkw0g4yLdA0lC95JBNqDcgKoD'
    'p1KAnWjkFoYYBhkDlAHArQGSQRAg0+EI4KkEEDgGBqxohT2GQKBpFAfkCQrMsME9gUhAq3KA'
    'UDxhDMP6AAo4FRILBgc8BwEVAplMBUAHsWlGgFUuEZQJbAB/gb6Bn4AYQQugBIWBzgVgcTpw'
    'Wg4Wr+A2cSgpikAYugCigShEg6wIknoBwVQ8xQEgC4KBRgEgUQgFwMpgljgC0iAzycVIIZiR'
    'SoMDzNEFS+B8wRA0ugfMIISCufAEFoKUBCKEeC0IiAgvhKgOmgMlACHQPUSoC0oDfFJ0QwQg'
    '6QfbUmYfgQCBARL/ejCew4yQUmKAxCgVVCz5DpJk5Birk1LoCGKIZndA6UagAERTxAYyBz2g'
    'bAEziEAEjYwMNAYhBOE2IDDwHpJOEgmFknIJAVKSEzCmBCB4OAYMhTk0Bg4GQQgrIUVAyRlC'
    'hRCFIGZJS2ADOjVSh9DAoQAgmTBJkRTAIKBspwAvaA16nD6BJD0vcCmBEVEFUTOAdK9AbpL8'
    'AMBIgwihUgQQkhQGwoGKAFBKypRNDXmMCIIUCQGIyiwN8wwSoF8aB0eqLWiBEBBeA0coCAzf'
    'ARIgGCOMsDJMNEMVYGeGhJyymKBxMxzH2uLNnA08IIqAYAwMaFKwm1CdNVMQAZ8R9lIC5lpk'
    'Eh7A4eNZkw0UsN5oDaNeWQwJsAGKE4FdJELw5DQgUlBiwOPBAOCBEG7Q+tAIUrBnhMAGKCbI'
    'AH0g0+IPqWMgceRh+vAeHqQtbrs4HKIDN0pRShFK4mEotyUbIII7E0DTZHDUwB/vCp9Gn1wg'
    'vgb9uAxSJACgMDxJihQKB0FqwoV4FRBAQoFA8wAhQYJCIXeChPzVARYChDzVATbEP0OLcm0B'
    'hzlXQWCgqtHmB+oQyRLfAdEvoAjgeCgb9QQHR8gDpWMSBkAEQT8Kgmld+LXQAEjEqA0cA8DA'
    'ygtoAISVhoKUgFAoGelDAChQNKAkJAvwFwKBpBXERABQJsBwigZmUMAUFQwFAgIUDFAkGKgK'
    'BIgCIUDKAEGqgKBDAGoUDSyhk5BQqM1gMCcUU+iyrNhg+FlAEeAD74oJlJ2QGpAEwoGHf8AQ'
    'o4UKKUCV2gOAgIHUcCoAOJguYBwUaAOBQM4CgZbHAmADiYLmAcFWgHBfgBgUlhgL3IDHhYAD'
    '0wXMkQHhOgHBbgAgcFZBSQiCwLJMFzHEGQXoDIVEAIMggAdqIFI0NAbpWgAwU0IgcCGmkGC5'
    'jSYQ2X0BsKSAMGygAWCgL+pGiFw8Bhg959AZgwrMKA2oKBsHIDRg02QwXMKQYRQGTcU+g9uQ'
    'AHEJ2oDUgJmKKJfAFPjJCgrEMlBWBQreDIEMgEE1IGDgZ6jepmJACC6KA0ZUAD7Ah7lh2yA6'
    'CGVAoiinP/LwDrXID/wPFhAbJGAwUgNWXnpCmB5gSBinkEiDijNg45J3IDDwNFYDAwMNQ4Dj'
    'MAagQn7GQA4ECaOuoD5wA4oDdDQLA0TSDCBnEksDTuBIGcKXAArQ5FSAx8AIKA8Byri+A/6a'
    'EcgIRAACTQgnCJ6QGAAMKoaDgThQGj3EBd0B+H/AUnAaBU1dAfbqA2bydgRirjY2GgDhQRDK'
    'w4GWg4O2toXNzZ0AUDBhVyibQ2MicBQc0CYSHeTgfIGDIQoG4U8HQBgUGVewIggrABoO1rJC'
    'h1UETE3pRJ0NnUwBzwOB/cbAKAcGhJ1dnCxMYHB2Us7VxcS2oAJBqpaZmLvRKluYWLgD8UFS'
    '0DiaSst4DdiaA8Dgw6mxpaGNqRAGD6CwAODwJQmI2lg7DiViskUB11tAikr29rbEADY8CULK'
    'hm6mxAWBLgIZe0MTUgArGCURNLF3snAjVGOkYCI08CFQh2AQQSppa29namdgD/QMDgCpYqAB'
    'CxC4AqHwoITLwKHCgeCCYWOZA6GQYJBQYUtJ5B+C6Aq1ZG1pqBqADU4VEFApxMAWWLDVgAoG'
    '1F6IcLzjkVEwiVEwIICpdoR+sQIOVAYFBI+EBAYHFSxuq6A15Z8cAssLgDCq32AXgrgTeyVl'
    'UBTxD6nisUMvBHsTxADguio6EVEGUYXAL9FOBaClQpZeAsYPwDAmIpUPREQTCmdiCkxkXCGC'
    'rgsOMYIQCAKjURsQ4rQLMVGQhgKqBQNwKQllCpFhDLKGwtZxQe+CCEAVwGgKbSQFA4gEOXYA'
    'wDDlcy4JfiAhDiEfDgiAnISyEALEQRlQArU4AXRgA4HOiIAfKAK4DkVRKhQYXCBBdoGvAHcV'
    'iL8BHgwYhgoGxC/FqJ4AqFhowBUFQABgQEAghCkkFAwUJBgQMdi7QrFRBiuCsIMLUTgCUFin'
    'gHBPALC8IcLAA4JoGIQEEAcLwCHCAxgC8AgIQYIcArBeApgIACwGoqFAAwwSgQKEQAEgKI8I'
    'BwwcXwgQoL4AwCIAwLAIIQBWAcCQCAgGMEFINEIAVT8Bi4CiVAqBQVUcoFBVQqg3WAXQgnWE'
    'FGAZ+sQIzDrR1YIIVQEGn0S+WYDbInECKL8pQRSjxoaIB49AdCpSbEh6g7KIQOFAxCJwoHSH'
    '0BcKB1gB8VerGIASKQjvCwAUICIcqkDcCgsEvojjhK9GarVyA4IB0FAxmWCnEQvBHLzBMl0i'
    '0gEi7gRShirAZKlIDEAMQcDRFKAoVJ2gbkAcKPyS/CYAoo5iRBbVRoYkgSSgNYwl/UJkyjEp'
    'A1bcBtMhtTYBFFA/gBHuAxAsTMAETUBg79/kgkQel05oCEyKVoABhFAXgwSTKisqJhgJQAwi'
    'KSKkG44DoIQAYFDYzjAT8wVUIEy0gMwZoB0oDDFSFNBoPSHiaBRE4DAvMQQDBeAGsCizAEBC'
    'w22AEJmoHSgMEA4RQGmoALM1HC4KNlQASD3AQFA3UDtJMGGkMWUAYG8hbEhOVAYSjQCeQG+U'
    'LJ3gXAGCmS9IGsKWAzPxGjiBjwGjiBpwFDsB8zAXQAMQLdAbgJ2pIHM9J2QxCEaAhFgleDoL'
    'BzAiAyILWYgwYwSSm6A3xS4GZQIMVWzQGIEwYhYEnA7iwU/k94WYCTDwQAEniYSUgMYZmhCO'
    'yA0uUgTgTjyGSA1VADxmwOHqwNT1Ab+ACi7/bgDDkKYAYhgYTT3EBL1zOCpgLMCunoAAc95A'
    'ZMgDwBOoC9wI6iTMCgg247ggkhyHUBl6Vg5QCDKYIgMQCgdb68SkB6KMAFhbQD9IDNgDcmAC'
    'oGBuwAoqm2A29wCrcA1KMEczBXh8AggAsoTB+9AJEsA4cgop0AgE4W3KA5YDbgAsyJkBkoLU'
    'CtAdF/kl/4TFKggPMDFkEA8JsFG6AmfuQG44S+CJD8APi5KNUpxAAZ88HWpGASygN6yuJECz'
    'wYXBgMoAPA43fk4BIIoQGwAIQFCDBBYmo3geRNcAHAEFADGDnEmcCTKB3gkDiAuABCC0IsQs'
    'QQjqSWhFwAxFs8dgbiDxXn/ppHyOogjeXBIgBUoD/wEEpD0Ei0lyAxKjVBBnhpUhQAtmYg4K'
    'qgN7AJFMWtyH6xQoX1ygPBZEDF1CAKihAMkQGhAIkQG6tCLSDRdQBMAWDWTgqGBBIOiAiQUA'
    '8kwLDFkaIuFH0KBlSAxGoEOA5A2gISgJQapvQOYl8MlIapEGBgVSwHQuGEhIgMOIAyZGhFiz'
    'iA19CgHSiiAgSY4GoR1E0MDNwVE+KgOAAPQuxA30BSzA2aIQLxR2IrKAA1DgVghmpAwIUB0B'
    'gYwCQdCsTMEIZBfALQjgHkGBroCQGBrcwbIEIon4AfUMgkc99gMQGGZgmOKhgaAxBK4n3ClO'
    'AyeGhGRgA8leKINA6UgNmIIFgpMNAOjQDvXA9hUgRT3BoCIvezQ1bQGrJwNwuIZDZFAHCZZM'
    'ADdYDhgTkmgSJwnFtBu0ji86gOGBVIB5gaihJK4D5gYkchsEwu+zKiDi1weCa0aADAJSidHo'
    'DZnQwFU4ga6A1MkBkgFQewDQAgwINPUNSoDP+ZwQVVgNgankgOglQBoWA3utgeAyK+EQAEsD'
    'KlIC1jAhJP8oDJCgQM7iDoRrloASFYIyiSW4kjiDqKAW2Ax7iBnAhOIM5i4gYGGmiC0TCYAk'
    'Os1RdQwFHEBoPUD9BAO/wLnAD7gAIDqQjQpoGIeYoguFb8QGGAfA4GRT5MX2CfTkRBKDcz4h'
    'gGG5oMBQfmHEBww/MmKQBrMglzgQCgdBlpANNKJlSgaGAkvBNg0VSBmpgB/FIEukBlkn0wR0'
    'LMiA0ySAMsrWUDSoi6ICYJsAdu/PKbApkkFUAwSTVNAk1SABE9AwMNhnDmwTCgMzRAbAAKsB'
    'igYTAJFzECAIcICXIQASRiWFSgllSAM7YDJjCD6JDzMAVhHnFKgHQEBkngqaBQOpCAAzMALS'
    'uNRkDjFA79KTELYlgCmfqmQAiYJWHIFhQYDHWyAESVBQRBZABAmjfJmUEnAQKs0JwADJFHgX'
    'IC/JYGiU1CpiBMQMqC4CCBAJKhkrgBgchmgxR814LQAeBVVJC5gQhKLEzFEMTEFBKAIFRQph'
    'aQFBMYaDPCgDmFaQGVjzIUMhYA2wGzGgIIYPqYARtFCp4BQSacg63+AKaFgHFeEgYQhDCANo'
    'MCci2YgZVnQAloe4MiEjwCRAJT3sBgVlASsQRInRIgMCPxA5d0gj8wMDA6SYAQKas8kWThD2'
    'uVVnUsBwkDPKrAbAyq4BsHKogBFHAYhUOIoDAjgEShpmGC1BEOMAz6YEzYHORGAQQO8gbD5L'
    'FVANmRNgjFBAPbYDAwHzIDSwJNQAtgMITTZAhHF/gkAeVEC5LQBplmzxWSmIbBlKQSYAXFE5'
    'kZDMFA0QYJmaFKC5jZh1PhUIMg+QEDAzpNgjlKgHAgSM5QWDArIBuFl5mBBzWA6VhCAzFNMF'
    'aigNMAhC/IxohILEAIQAJUBRlKqCcAQqsrRmyoLWMDAYpNCgPinQBliA28Bv1AyupSI3MQGA'
    'ajmJEMAtnMIIRBouZAQhReUouYCHSA1+TNmAL9eIrW+IQDRnQ2A8VEDYEwiAtAbBGFzFJAIT'
    'FCAvAATsB8wJKAALVDAZJGAvlGhHCQOinAYCwGoJAGhok0ADWA0+Yg+3KmnyPqJgB/e0KYov'
    'wMnyiHQpTV0KmpBohumAUDmSE3BGyAxCXzFNPMMUTR+nuVdhIHkAkBQMsxAaQUhAyQhHQGOw'
    'GfVBAAiDIWZOAYXA4QaRS2QGnARWq4DwSoedogYVNAgwCeJO9q5mODAVdiaMAODqEzJCEgok'
    'wNINFeYBxEgFynwcGVcH9YDOJJwIwjAEoqsBeriQUwA1gggqUMEdBnRDAKAA6miUJiDsFAxi'
    'RwAxSAxacCkIlBATYLAmiPowOiA93iBcEeAMBoMWKUCZAKBCAIgUDL5MNIGUHywgZSgikDEG'
    'BQQ/0EELgvgHUBBngJ9IbgoG2CIBRuAGZHAUMBqImB+AQZaBFpAZOmBE5h1lMDhMBAjySVBU'
    'Dg4HYPcDISwAFM6hBMigYgaQaR0wDmIDFxCC5Mo8Bh5Af6Iwi6CdSeZomMCaIDAAGBTmGZpj'
    'AGIAB4KVACIUL4LFXp0HwSADhD6bA6pB0mEDogC7Bon9sg0CEgaA4HUO0GgXkAoIYBQqBeg/'
    'yUCvis0S+IEpDkTrEBpwGeIMQGlQEwgyvEGh+QgRAOUAhp6yAtypgOchYFBmpAZ8GBiCCgg+'
    'HtOQF8oCAuqcygXFKgJoQ53MXACBecJIKYBkGSCJmJEwAUIKjRIZ/AUkgMCEGchMzAm4HMCA'
    'xgAdogKZhhNPMC1zJCUBBp9APlMxpSFgc+nApj0O/yNUuAFkpTKAngFASqEYaGRiAyoV5+gE'
    'JQjYEoKBoglBEqD+QpnBQV9PgAFZhR+AMJfqClO4ASb4OkCf4QuAAiYeQF4kHqB1qapGDKI/'
    'BC6EWYJIWwTgwRiqw0F+bgJAsgFWJ2GC50UAIZETGCkAsxQhGjOqURjmYQUuLmo93EDKIc/k'
    'SaIXIB1/P8EUqNKQFzHTUBZB+Af4AgcoLOgKAcG8FcLgAwFCAoGsBQMnk74gJ3AQUQnACgwI'
    'QPAdWHAT4B+xYAVoKkQdTFKQYHEg6kgoY56gYC1f4A8XACZKQGLEB8ypBiLBL5ATYVKs0UDN'
    'ZawJCIDMC5wboAgdDAwQBEHAwEBBEPRREMPAT/Qhlj+UHRAcABQigb4AsgAA1cwxBPRAagzM'
    'CVBFnADO5bAdohQmF4ZQSkIGRwDk8cDfwcNQ4DjMAagQn7GQEDUEg2B5xKiX9hRKwNEtgALq'
    'pFDP4AGy4MqQktD8PqQIpMkkvcAQMFwB2CwOZAKMdkQANpiBRwA0IPFrgBpFWf+z4UvCACVw'
    'cQqQUyWhouD+g0FDQAOBG4ALuSGCYpTwOtSINgBEKHgAGegBBy/yQAch0YRmEEG0OMpCA2ol'
    'IB4OSGOoGnACGUX0CgJ+BkigbkPeB5KVCcQU+iJrNhgKFDviC5RQn/n+FeCirM4C/gQZ+AEF'
    'TKAha4ZNQklIBIgMosQcGBeAiCQLMkC6gQQEGQgfBNgEwgoA4qdAQHJFBQYa+QRhcz7/Dz4m'
    'NcAWxBuAwSZUTkBLYqJkGm0BKZmCA5X/GIGEAFJdAYOI2Bga8lMR7gCgimM1I2I2TMEJwgXc'
    'FECpgOsByE6AbFMpAgoNxXGSBUQNEXQwAg/QMgWRiFnwB4C4kzIAdABeB2GUmFgYG+IUQnJB'
    'GcKBg1QIXAH5KAqoDgZHmgQVEwGIr4H68P+D8UHA8JC5KkAFnHmCFICZlBj0OWB6KDHWUBFg'
    'AlAXFIU4DBCF/3+RLYgL/f8qRw6BwMjAIRQAMocyi0PFAKwBFoZYKACANQHK7wCBhDzBwJlC'
    'KQBxUn/l8ByAqQfwjYMQILAigEQSFIG2Y/IVWBwQKgEGVACJ/DICMyReFA4CRgICtJ0gPIBG'
    'gQcByIqHACCIeWIg030BQi4ggxlQgwAAMEgKDeAOAigDwKBgpSAQAAKJ3DOiHUKBpk4CiAbC'
    'qEzTMBQLQBsHQpSLBsQWBNwFIUDJoeAYGwcDL5KiIUsIgYQinACDAaBmYEGA7oMoBuBiYGY0'
    'SDQAiYI3AHMIPQAiYO4CxAEAlngAGREEAIEQfAFBxuwEIUACBOsGAkUC4gbBeANlKCQAegxy'
    'Jc4+AwHKBBgBFfnidwFyA3QA8AQHcIAY4OAoVkFwA3EEEv0DLDAB+NGX3AfDlXQCQYcgsDW8'
    'P/wI8BewKnABcD9wBvAjyBwIPQg4SBNiOmlNrygiIAXASkxdkx1MBYKLDmzwJ4CBSB2WyMIE'
    'coHtlBQO0tABF2lAwS9gVsUDOAEGEYINOhsZGTADlDvHoKbxINcA/z7AuJV7URdHA5gOB2OI'
    'D9k7WQEJIPyRgcBHQMD38oHlQTVRAhDor0FI2WI7axAfcCjQQbZfIlIcDQ68NnUycXYgqisr'
    'KScuLKZM0llaQImELRLvZQRAoIMfk2BpywdDgNU2Fr5QP0DgaUJdU1tbIyphLmBg0QFAzRQh'
    'MA4MqQYfUMk7QiUQHDG0svUxCocCzgViaDKqCAECRQRVBAnk5AkkVAnVJGRkCIVECGXllFTh'
    '3VDh2qaD5SugcDybMA4dEgg/UDB/gIqxCqNc4D0UWhb2NkKoUDUWhxtDY2EgNBiwMDCAUGAA'
    'iUQHBC5hwP8UFAqxthwPqqGLoZOLsSop3tbAmIWtDc0tA+r6ey9oNHEBgZDLbJwLqQeWYKB3'
    'DTSaWPB9IMD3qlwIMJB/IUD7gbk9FbBxdPY8wsG+QRZFV2cBZAQegK9USgQdqEg3yEpBCgei'
    'DA/amgRF7xGL1gQFEUUm4GJUQUD9g6CJQwPWM78qxCzV2cjQLhQ0C+psB2BgacBIuwsbdBdM'
    'Zm0C0VaSYEg4OtQNSVOpoZDYPMW4HXKRT0VQCgdwEgzkVOTJgrQOTvbGBYwFMZ4tULpawILI'
    'DRxhaBpGVsFTgHkhUMAQhq6k6WROTzAjNDY3KZKJVVcQUDhgZlqFUPaGBN1KWMPsCyLIU8Cq'
    'qYCYAQ6IJB6gUDKgNlWljAYGUSZDlbQ3MhsFQA2B4NcH4jQEhCTJFwtAMtW/C90NnISRLlCu'
    'DiaGpyRM6AiAiRq6WNsTlaQIKJUo6AFBQuUAqEUBEa4Ze0MTEMIgFcIoO0MQIKUuSTsTUw8w'
    'YCgdEPSxdgUAQedDNyLwBBo0NjawBNUkKeps5CoLkDQnb2hEAEMASqYurk52YED7OxdLO1dT'
    'MgIEAYBoOizsZcBMaGdsarGwBgfd8L4wAAAlug=='
)
EDITOR2 = (
    'AAAABuI+B3AQY2BIigZoACTEAMP+ybEUkoKmIDukw/QYQkWA14D2iAwQ8hACqgRSiACAfGHg'
    'T8CBK8SSQIwBlBDiSdoJNEEQCIAcHRAoGESJB5oCXcFGCJBP0KZRAMKkW4ALv5EGASARxEQ5'
    'FVEAcSCw0Q1IwPKh5YDQlWGRUmEAFmFLoAAyKRYeIGwPQHB2JEB5CIQCUEggIpy6oEDAVQgY'
    'GxWSAx5FH0UPBAYJsA8DjYrYnBmRAaVRLqHkaYHDLSkQc2PaPVRVDgAiulA/gBdDAzSSgVSZ'
    'UMEfAoFbABGRQTumweKoAAIScQgEYEF1NABUEtuDXgB0PIDwA1UbAwK+mA0gwEvjbMmACW8Y'
    'BRFI4DYqEQYPBLAJEQ0A73YUOU0HuSQShkFZIDeJQm9sBqA4DhxkNYGYiQIYQA4lgoKTP0B8'
    'UBhkESgMDPoc1zB0FtkB6CMrMiQCKjJ2LJj4YJLIDEC7gBMOwsxVAcEbgYNwUaNDLTIAMjkC'
    'EEOIwHKLrAy7+BAhEFOMkpFjcHNwcMRZCg5iANyWYEZAMaEcDkuIDB1LBZiiQo4IXQIDmEAf'
    '4Eun3B/sCGQGDsgNMA9FeQPRUuOBggwiDAHwofCFgIDA4Hcg4HICkAGG1SDT1AyIUwkBkyJB'
    'im+ogKwBpBgbAARmYQUAdK2BOlwAPVbGqdUDTe0GILcBZEB9QkwDCenSAR3QWI+BmFnUoGBT'
    'IEYEKAuClBQKhABxXVKDQUMAiCqgPW4GyCuKUDAqwCSSDwWoCwMhOGFBYhEAqFA1tqBn4lCl'
    'BEKXwUFSdouD8VDaCgCBOwD4UDVRL1KBkVLooOUTSTzOlEv9ZEx3qgbcADwA28VDWCEgNQ53'
    'MzICURNSilYTbAcrbAYuOwUIEJoBXIDOhPgSENQgABYHhQlkAiSDUinCWBSDxUZagZIIfFwO'
    'moG3AKShYg4CrpB5UAixATBM4uCYVBa/szYSCQJwAZ+AfcqJPAALDRTC3A4qB4gHtYOCAoyy'
    'BE5gdPJcMcIYmQG5cwMQLDAjJqAYj/gPGEGHsgkgEa9BQM+pAYxmRUYfFUiwsFnAVCTANpwA'
    'CBtUqALxQMYokAMEbEKAH9TEACfAgAAcS6gSnBh4NvsNTYmeGEhofM9qTCzMmEvtYQAchaga'
    '3FAw8TkAc0E0oZMwctXWQGvgFcQGPgBLwA1E4NNIQZAA9qcNgjFgNsIgYGmHlB/Zoi1cKcQG'
    'ZfeAgYTYNPYQEPxMAQlUDxP00CiqRQgQE5AIDOc0BCKVKARBgBATEDaJszQI5RLQAM8OEUC4'
    'CICBczgSHhGCnEJNPcFlegTMjFtqABbMdFE5gcWKRgIBLTyAxMxlZIMb7DwBqAJgCYpUpBQ1'
    'ZghpEBjwGCGBXpx2ADgAPmNKIDDkKCUKEA9m8AnVWQNwrgDwWtSdEMEIAC5ApmHw5CrX/Agy'
    'PHAz6R4kGWHnwBYWBoAF0UDDoCCYKypQLqkwDIRcQgtVSCsgGQOBigcDZhCDKHAxAWoBoDAw'
    'YDyDA5KygAkkABAEqYAKBbAL4h4BSqEBWEMAGl1osAZCfh0BRqkBkEi9JBBNVgLUgEHapFIg'
    'D8iESBQbZAIZAdiA0T6gMC8AhsAFyIeMyKsf4NcxFICQGZgLWgwEyDQLMq04BQTJsAEfSLgA'
    'oNOOk0oXMCYXIwCgalhKyhh4kaeCkWFlYWHQQUAwiA18BeKCjiUxi0v4AzBAhJQ6qx5hCADI'
    'kAlDDyAeIYAo4YgMyAwSCAbEcCgdpJAAJgsCgZAVdmSLDx8AcH8PEgP4ZkiGBCFUuAdAQxlF'
    'Kf+bhx+DIEM4MHGg0GsTHBUxl5giDAKcB2kSo5mEA4AIQDfgIIOAESITsBAKBiAGIUwYmjAK'
    'BU0DAPMvpDpgRsoCZk/BzegBBggIFJEgGSQROQLEkk/ZB+hplgLOgYBV6fA9UWABU/jgsFDv'
    'EKAhE0CPAaL+AINAMDebyCgIAAIKvACKrggGBtIYaICIDPoGkAnwCAXgEALIFzgB9wAFB1WS'
    'wBANEhGgAHMX2ITgAwAH6DwDB1ASAQdABAAGjq4QVAFG4AAgnwwzDgeEv4B0ncAIxhh+LAGA'
    'j40Ip1AQSkUAEFYrAX4HdIICkNMwxQ7KWhQM8EeAeRbHcHAXi74H4KBwwbBTFuAPBQMWv8Rg'
    'SSdcIUzgTqrBYPHPA1VwOTMhQKhfrybIP1eAYpGALsQUPJJAxh8igalBMyIDDAafcRImWE1H'
    'TBKMUJUYRgjCMgmRJIwHW0/9zQ6hQPy9wAewGFOgoGSCUEr4V4clywF1O/8OApYHAQQEUg4C'
    'TjxipI5HSAQAeUbpeDgYEBIglg6H/UplmMCHRQQBGIAAajAAdQ71AOEgBBRHrOUgIDkhyKD5'
    'QEB4EJgA40W1VaBYoFVgaGGV0AjIonACCAKBw8ikLAbAswxxRhgZOBRhgYgBRquSvUHuAAOA'
    'g0ACmAg1AUpSgoFbQA4v6lBoKKgWhdwA4MDGivylAwKkgaoolZAWlHril4E0lkJgOyqwA/AB'
    '9/0DoIyA08x2TMwJSA4QZqDUJUzMwUhzkcSSgINYuYkPADuAm4bBhEpAWhQM6lkAYCuAMIMY'
    'INl/gfyugH6EOCHVcxBBjKWcZYggkiCgfwwnYBINkEKpQDgWrRg+lk6mCYMUlCiAZLmEINAc'
    'DcIoGJc/8/yS/TKiASFCNgBhIoS+nKSFAoeBoF4UoNBUcDpBbhloaSoIUDeVKBgUzAmTKLIF'
    'AwMAiJuARCgb9AQKhBwFRRQFncACC1zeAUJsAKFwlkEkj6AIhT+WQQrWA8yiBgFAAwVQAZEH'
    'ESgBalGCF+DNFOf+D4Yh/lIZZhYhEK+lcT6fEAamNcJBRGOWfonihwEgd84gWCpQUCiHouBQ'
    'JUAQeKfVWYswhehlUS/5k1Wf0Qo2AUw8gDtMW4qT/z/A5AKSAQr8IUgFmaKNEPlYae4gL/H2'
    'ZQDm8GYA6fBkAO74YAPxAy+/5/cq4yorLKgmqiAOjkAgQECkJAAADQAAUQAIB8AAQAyGAu8H'
    's2cbTAAAC0A='
)
# END GENERATED BY build.py


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def embedded(name: str, encoded: str, digest: str) -> bytes:
    data = base64.b64decode(encoded)
    if not data or sha256(data) != digest:
        raise ValueError(f'Embedded {name} is missing or damaged; run build.py')
    return data


def directory_entries(disk: bytes) -> list[tuple[str, int, int]]:
    """Return (name, offset, size) for every file in the disk directory."""
    if disk[DIRECTORY:DIRECTORY + 12] != b'Reserved\0\0\0\0':
        raise ValueError('Unexpected disk directory')
    entries = []
    offset = PAYLOAD
    for record in range(FIRST_RECORD, DIRECTORY_END, 16):
        raw = disk[record:record + 16]
        if raw == b'\xff' * 16:
            return entries
        name = raw[:12].split(b'\0', 1)[0].decode('ascii')
        if not re.fullmatch(r'[A-Za-z0-9_-]+', name):
            raise ValueError(f'Invalid file name in directory at {record:#x}')
        size = int.from_bytes(raw[12:], 'big')
        if size <= 0 or offset + size > len(disk):
            raise ValueError(f'{name}: file outside the disk')
        entries.append((name, offset, size))
        offset += size
    raise ValueError('Disk directory has no end marker')


def repack(disk: bytes, replacements: dict[str, bytes], additions: dict[str, bytes],
           limit: int) -> bytes:
    """Rewrite the directory and file area with replaced and added files."""
    entries = directory_entries(disk)
    names = [name for name, _, _ in entries]
    if replacements.keys() - set(names) or additions.keys() & set(names):
        raise ValueError('Invalid replacement or duplicate file')
    files = [(name, replacements.get(name, disk[offset:offset + size]))
             for name, offset, size in entries] + list(additions.items())
    if FIRST_RECORD + 16 * (len(files) + 1) > DIRECTORY_END:
        raise ValueError('Disk directory is full')
    end = PAYLOAD + sum(len(data) for _, data in files)
    if end > limit:
        raise ValueError(f'Files would end at {end:#x}, beyond {limit:#x}')
    result = bytearray(disk)
    result[FIRST_RECORD:DIRECTORY_END] = b'\xff' * (DIRECTORY_END - FIRST_RECORD)
    offset = PAYLOAD
    for index, (name, data) in enumerate(files):
        encoded = name.encode('ascii')
        if len(encoded) > 11 or not data:
            raise ValueError('Invalid file record')
        record = encoded + b'\0' + b'\xff' * (11 - len(encoded)) + struct.pack('>I', len(data))
        start = FIRST_RECORD + index * 16
        result[start:start + 16] = record
        result[offset:offset + len(data)] = data
        offset += len(data)
    if result[limit:] != disk[limit:] or result[:FIRST_RECORD] != disk[:FIRST_RECORD]:
        raise ValueError('Protected disk area would change')
    return bytes(result)


def jump(address: int) -> bytes:
    """JMP address.L followed by NOP: replaces exactly 8 bytes."""
    return b'\x4e\xf9' + struct.pack('>I', address) + b'\x4e\x71'


def hook(code: bytearray, address: int, original: str, replacement: bytes) -> None:
    """Replace original instructions after checking they are the expected ones."""
    expected = bytes.fromhex(original)
    start = address - CODE_BASE
    if len(expected) != len(replacement) or code[start:start + len(expected)] != expected:
        raise ValueError(f'Unexpected game code at {address:#x}')
    code[start:start + len(expected)] = replacement


def patch(disk1: bytes, disk2: bytes) -> tuple[bytes, bytes]:
    bootstrap = embedded('bootstrap', BOOTSTRAP, BOOTSTRAP_SHA256)
    editor = embedded('Editor', EDITOR, EDITOR_SHA256)
    editor2 = embedded('Editor2', EDITOR2, EDITOR2_SHA256)
    if BOOTSTRAP_BASE + len(bootstrap) > BOOTSTRAP_LIMIT:
        raise ValueError('Embedded bootstrap is too large; run build.py')
    name, offset, size = next(e for e in directory_entries(disk1) if e[0] == 'Code')
    code = bytearray(disk1[offset:offset + size])
    if CODE_BASE + len(code) != BOOTSTRAP_BASE:
        raise ValueError('Unexpected size of the game program')
    # Reserve the editor's memory when the game sets up its file cache. Load
    # Editor2 from disk 1 in place of the game's first search for disk 2
    # (BSR $3C6E / TST.W D0, 6 bytes; the bootstrap runs them afterwards and
    # returns to $510). Load Editor from disk 2 after the level metadata,
    # before the main menu starts.
    hook(code, 0x3916, 'd3f800082b4900f8', jump(BOOTSTRAP_RESERVE))
    hook(code, 0x50A, '610037624a40', jump(BOOTSTRAP_LOAD_EDITOR2)[:6])
    hook(code, 0x548, '610037fe61002730', jump(BOOTSTRAP_LOAD_EDITOR))
    code.extend(bootstrap)
    return (repack(disk1, {'Code': bytes(code)}, {'Editor2': editor2}, DISK1_PAYLOAD_LIMIT),
            repack(disk2, {}, {'Editor': editor}, len(disk2)))


def identify(paths: list[Path]) -> dict[int, bytes]:
    """Read both inputs and match them to disk 1 and disk 2 by hash."""
    by_hash = {digest: number for number, digest in INPUT_SHA256.items()}
    disks: dict[int, bytes] = {}
    for path in paths:
        data = path.read_bytes()
        number = by_hash.get(sha256(data)) if len(data) == DISK_SIZE else None
        if number is None:
            raise ValueError(f'{path}: not a supported Lemmings disk image '
                             '(SHA-256 does not match)')
        if number in disks:
            raise ValueError(f'{path}: disk {number} was given twice')
        disks[number] = data
    return disks


def write(path: Path, data: bytes, inputs: list[Path]) -> None:
    if path.is_symlink():
        raise ValueError(f'{path}: refusing to write through a symbolic link')
    if path.exists() and any(path.samefile(source) for source in inputs):
        raise ValueError(f'{path}: output would overwrite an input image')
    # Write a new file and move it into place, so an existing file (or a hard
    # link to an input) is replaced rather than modified.
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, suffix='.tmp', delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(data)
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=f'Lemmings in-game level editor V{VERSION} disk patcher.')
    parser.add_argument('disks', nargs=2, type=Path, metavar='DISK.adf',
                        help='the two original Lemmings disk images, in any order')
    parser.add_argument('-o', '--output', type=Path, default=Path('.'),
                        help='directory for the patched images (default: current directory)')
    args = parser.parse_args()
    try:
        disks = identify(args.disks)
        patched = patch(disks[1], disks[2])
        args.output.mkdir(parents=True, exist_ok=True)
        for number, data in zip((1, 2), patched):
            path = args.output / OUTPUT_NAMES[number]
            write(path, data, args.disks)
            print(f'{path}  SHA-256 {sha256(data)}')
    except (OSError, ValueError) as error:
        parser.exit(1, f'error: {error}\n')


if __name__ == '__main__':
    main()
