#!/usr/bin/env python3
# Lemmings In-Game Level Editor V1.0
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Patch Amiga Lemmings disk images with the in-game level editor.

Usage: python3 patch.py DISK1.adf DISK2.adf [-o OUTPUT_DIR]

The two input images may be given in any order; they are identified by their
SHA-256 hashes. Only the exact supported pair is accepted. The inputs are never
modified. Two new images are written to the output directory (default: the
current directory):

    Lemmings_Disk1-editor-patch.adf
    Lemmings_Disk2-editor-patch.adf

Requires only Python 3. The editor code is embedded below; it is generated from
the assembler sources in src/ by build.py.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import re
import struct
import sys
import tempfile
from pathlib import Path

# The supported Lemmings disk images, identified by their SHA-256 hashes.
DISK_SIZE = 901120
INPUT_SHA256 = {
    1: 'a4fdba69017f1a760bba3bb06c55f7e434226c498c9d22c1f627212b08d24f91',
    2: '1526000b96d196efecab9c63aa72c0ce6257649a4993141b00ead8738fd97a65',
}
OUTPUT_NAMES = {n: f'Lemmings_Disk{n}-editor-patch.adf' for n in (1, 2)}

# The game's own disk directory: 16-byte records at $400..$13FF (the first one
# is reserved), each a 12-byte name and a big-endian 32-bit length. File data
# starts at $1600 and is stored back to back in directory order.
DIRECTORY = 0x400
FIRST_RECORD = 0x410
DIRECTORY_END = 0x1400
PAYLOAD = 0x1600
# Disk 1 keeps its raw boot loader at $CA000; files must end before it.
DISK1_PAYLOAD_LIMIT = 0xCA000

# The main program file "Code" loads at $400. The bootstrap is appended to it
# and must end before $21C00, where the editor's chip-memory workspace starts.
CODE_BASE = 0x400
BOOTSTRAP_BASE = 0x21B4C
BOOTSTRAP_LIMIT = 0x21C00
EDITOR_LIMIT = 0x4000

# BEGIN GENERATED BY build.py - do not edit by hand
VERSION = '1.0'
BOOTSTRAP_RESERVE = 0x21B4C
BOOTSTRAP_LOAD_EDITOR = 0x21B68
BOOTSTRAP_SHA256 = '41bec77569fece9433fab4b5647a3344d4a4a395f00529f3c86a0d61fd3f22c9'
EDITOR_SHA256 = 'c648a6c3fcf7dd7171530edb42d414c2fa6c0a03d413e1ecc72247c3e8a4d4f8'
BOOTSTRAP = (
    '0/gACAy4AAJAAAAIZQaT/AACAAArSQD4Tvg5Hk64PUgMuAACQAAACGUUQfoAGiJtAPhyAE64'
    'MoYgbQD4TpBOuCx+TvgFUEVkaXRvcgAA'
)
EDITOR = (
    'SOf//kn6CqQgbQD4QehAAClIACBB+gEaIcgXUDH8TvkXTiH8TnFOcRdUMfxOcRdYYQAIDEH6'
    'AUghyAZWMfxO+QZUMfxOcQZaQfoDziHIBoIx/E75BoAx/E5xBoZB+gBAIcgnZDH8TvknYjH8'
    'TnEnaEH6A9YhyAaKMfxO+QaIMfxOcQaOQfoIDkP5AAIrADA8ABMy2FHI//xM33//TnVOuCgK'
    'SOf//kn6CgJhAAWeQhRCLAAuQiwAA0JsAERCbAA0QmwABkKsADAZbQAmAAJB+gfsMDkAAMXA'
    'sHwABGJG0DwAMRFAAAYibAAgcgBOuDKGIGwAICJIIAFOuDk0IG0A/EHoApBwAEpQZxJKaAAC'
    'ZwxSQEHoAAywfABAZeo5QAAIVuwALkzff/9OuCgmTvgnahtAACZJ+gl0SgBrNrA8ABJmCAos'
    'AAEANGAosDwATmYGUiwANWAcsDwAT2YGUywANWAQsDwAI2YKShRnBgosAAEARRP8AAAAv+wB'
    'TvgXWkjn//5J+gkmQiwANkDnAHwHAHwAMCwANBwAQmwANB4sAEVCLABFRt/gSEoAZ2xQ7AA2'
    'Si0AMGYAAJpKLAAuZwAAkkotAClmAACKSi0ALWYAAIJGFGcsGW0AOQABUO0AOQg5AAYAv+AB'
    'V+wABAguAAIAFlfsAAVCuQABRPJhAAQcYFAbbAABADlQ7AA+Qi0AJ0ItAChhAAQ2YDgwBkoU'
    'ZzJKAGcuUOwANkiA0WwABkpsAAZqCjAsAAjRbAAGYPAwLAAGsGwACGUKkGwACDlAAAZg7EoU'
    'Z3pQ7QA5SgdnCEYsAERQ7AA2YQAA+mEAAUBhAAFeCC4AAgAWV8CwLAAFZxAZQAAFSgBnCEYs'
    'AANQ7AA2CDkABgC/4AFXwLAsAARnMBlAAARKAGcoDHkAoAAAnaxkHjAsAAoyLAAMdABhAAHm'
    'TrhLOk64SnhSrAAwUOwANkoUZ35KLAA2ZlQwOQAAnaiwbAA8ZkgwOQAAnaywfACgZR4MbACg'
    'ADplNDlAADo5eQAAnaoAOGEAAKRhAARiYBKwbAA6ZhgwOQAAnaqwbAA4ZgxM33//Qm0APk74'
    'BkY5eQAAnaoAODl5AACdrAA6OXkAAJ2oADxM33//Qm0APk74BlxM33//TrgYmEJtAD5O+AZc'
    'DHkAoAAAnaxkPkp5AACdqmYSBHkAEAAAnahqLEJ5AACdqE51DHkBPwAAnapmGgZ5ABAAAJ2o'
    'DHkFAAAAnahjCDP8BQAAAJ2oTnUwOQAAnarQeQAAnajQfAAQOUAACjA5AACdrFhAOUAADE51'
    'IG0A/DAsAAbA/AAMQegCkNDAOVAADjloAAIAEDAQ5kg5QAASwOgAAilAABQiLAAgkrwAB1V4'
    'ICgABNCBKUAAGCAoAAjQgSlAABxOdUH6BpBKEGYkSigAPmcWCDkABgC/4AFnEAguAAIAFmcI'
    'QigAPk64C0pOuBTiTvgGiE64H1JOuEqkSOf//kn6BlRKFGc+Si4AAgguAAYAAmb4YQD/QGEA'
    '/14MeQCgAACdrGQUMDkAAJ2q0HwAEDI5AACdrHQBYRRhAALcUqwAQE64GJhM33//TvgGkDlC'
    'ACQ2LAAO4kuQQzYsABDiS5JDOUAAJjlBAChKQmYoKXwAA3CAAEwpfAAAheAASDl8AMwAUDl8'
    'AKgAUkJsAFQ5fADMAFZgJiltAMwATCl8AAAhAABIOXwALABQOXwAoABSOXwAAgBUOXwAKABW'
    'egfKQERFUEXmQDlAACpI5wAGJCwAFCpsAEhCbAAsMCwAKNBsACywbABSZAAAxsDsAFAgbABM'
    '0cA+LAAq0McwLAAsSiwARGcIREDQbAAQU0DA7AASImwAHNPAJGwAGNXAPCwAElNGcAAQGWd8'
    '62g2B5ZsAFS2bABWZQTAfAD/UkO2bABWZQTAfP8ASkBnWiZIeANKLAADZjIsSnIAEhbracJA'
    'NgDgS2cKRgPHEzYB4EuHExYAZwpGA8crAAGDKwAB3cLXzVHM/9RgHjIARkE2AeBLsHwA/2MC'
    'xxNKAGcEwysAAdfNUcz/7FKKUohSR1HO/3ZSbAAsMCwALLBsABBlAP8eKl8sX051SOf/8GFU'
    'TN8P/zP8JMEAAITuI/wAhAACAACGaCP8AIYrAAAAhmwj/ACKAAAAAIZwTnUz/PTBAACE7iP8'
    '9AH/AAAAhmgj/ACcgBAAAIZsI/z////+AACGcE51QfkAAhwAMDwDv0KYUcj//EX6AkZH+QAC'
    'HAB+BXgAfE9wABAasDwAIGcEYQABvlBEUc7/7kfrAoBRz//iR/kAAiEAODwAYDAtAEJSQGEA'
    'AVZH+QACI4A4PABgMDkAAMXAUkBhAAFAR/kAAh6AODwBADAsAAhhAAEuR/kAAiOAODwBADA5'
    'AADFwmEAARpH+QACHAA4PAGgMDkAAMWoYQABBkf5AAIegDg8AaAwOQAAxaphAADyR/kAAiEA'
    'ODwBoDA5AADFrGEAAN5F+QAAzYZH+QACKIB4AHwfcAAQGmEAAQxQRFHO//Rw/zlAAFg5QABa'
    'OUAAXDl8AQEAXjAsAAqwbABYZxI5QABYR/kAAhwAODwAYGEAAJAwLAAMsGwAWmcQOUAAWkf5'
    'AAIegDg8AGBhdDAsAAawbABcZxA5QABcR/kAAhwAODwBAGFaECwAA7AsAF5nGhlAAF5H+QAC'
    'IQA4PAEAcCtKLAADZwJwLWF8ECwARLAsAF9nKhlAAF9H+QACI4A4PAGgRfoAykosAERnBEX6'
    'AMN8AnAAEBphTlBEUc7/9k51SOf/4MC8AAD//yQATrgYYioAfAPhnXAAEAVhKlBEUc7/9Ezf'
    'B/9OdUP6AspB+gW+el5CGXgGEhjlCRLBUcz/+FHN//BOdUjnwMCwfAAgYwawfAB+YwJwIJB8'
    'ACDnSEH6ApTQwCJLMATmSNLAcgcSmEPpAFBRyf/4TN8DA0519AH/AACcgBABAJIAAQIAAAEI'
    'AAABCgAAAOAAAgDiHAABgg///////kdyb3VuZDEAT2ZmT24gWCBDb29yZCAgICAgICAgICAg'
    'ICBQaWVjZSAgICAgICAgICAgICAgIExlbW1pbmdzICAgICAgICAgICAgTE1COiBQbGFjZSAg'
    'ICAgICAgICBZIENvb3JkICAgICAgICAgICAgIFBpZWNlIFR5cGVzICAgICAgICAgVG8gU2F2'
    'ZSAgICAgICAgICAgICBSTUI6IEFkZC9FcmFzZSAgICAgIExldmVsICAgICAgICAgICAgICAg'
    'QnJ1c2ggICAgICAgICAgICAgICBNaW51dGVzICAgICAgICAgICAgIExlZnQvUmlnaHQ6IFBp'
    'ZWNlICAgR3JvdW5kICAgICAgICAgICAgICBTcGVjaWFsICAgICAgICAgICAgIEZsaXAgICAg'
    'ICAgICAgICAgICAgRjogRmxpcCAgIEU6IFJlc3VtZSAgICAgICAgICAgICAgICAgICAgICAg'
    'ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    'ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg'
    'ICBFZGl0b3IgVjEuMCBieSBUaW1vIEhlaW1vbmVuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQEBAAECgoKAAAAAAofCgofCgAEDxQO'
    'BR4EGRoCBAgLEwwSFAwVEg0EBAgAAAAAAgQICAgEAggEAgICBAgAFQ4fDhUAAAQEHwQEAAAA'
    'AAAEBAgAAAAfAAAAAAAAAAAABAECAgQICBAOERMVGREOBAwEBAQEDg4RAQIECB8eAQEOAQEe'
    'AgYKEh8CAh8QEB4BAR4OEBAeEREOHwECBAgICA4REQ4REQ4OEREPAQEOAAQAAAQAAAAEAAAE'
    'BAgCBAgQCAQCAAAfAB8AAAgEAgECBAgOEQECBAAEDhEXFRcQDw4RER8REREeEREeEREeDxAQ'
    'EBAQDx4RERERER4fEBAeEBAfHxAQHhAQEA8QEBcREQ4REREfERERDgQEBAQEDgEBAQEREQ4R'
    'EhQYFBIREBAQEBAQHxEbFRURERERGRUTERERDhERERERDh4RER4QEBAOERERFRINHhERHhQS'
    'EQ8QEA4BAR4fBAQEBAQEERERERERDhERERERCgQREREVFRsREREKBAoRERERCgQEBAQfAQIE'
    'CBAfDggICAgIDhAICAQCAgEOAgICAgIOBAoRAAAAAAAAAAAAAB8IBAAAAAAAAAAOAQ8RDxAQ'
    'HhERER4AAA4QEBAOAQEPERERDwAADhEfEA8GCAgeCAgIAA8REQ8BDhAQHhEREREEAAwEBAQO'
    'AgAGAgISDBAQEhQYFBIMBAQEBAQOAAAaFRUVEQAAHhEREREAAA4REREOAB4RER4QEAAPEREP'
    'AQEAABYYEBAQAAAPEA4BHggIHggICAYAABEREREPAAAREREKBAAAEREVFQoAABEKBAoRABER'
    'EQ8BDgAAHwIECB8DBAQIBAQDBAQEBAQEBBgEBAIEBBgAAAkWAAAAAA=='
)
# END GENERATED BY build.py


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def embedded(name: str, encoded: str, digest: str) -> bytes:
    data = base64.b64decode(encoded)
    if not data or sha256(data) != digest:
        raise ValueError(f'Embedded {name} is missing or damaged; run build.py')
    return data


def directory_entries(disk: bytes) -> list[tuple[str, int, int]]:
    """Return (name, offset, size) for every file in the disk directory."""
    if disk[DIRECTORY:DIRECTORY + 12] != b'Reserved\0\0\0\0':
        raise ValueError('Unexpected disk directory')
    entries = []
    offset = PAYLOAD
    for record in range(FIRST_RECORD, DIRECTORY_END, 16):
        raw = disk[record:record + 16]
        if raw == b'\xff' * 16:
            return entries
        name = raw[:12].split(b'\0', 1)[0].decode('ascii')
        if not re.fullmatch(r'[A-Za-z0-9_-]+', name):
            raise ValueError(f'Invalid file name in directory at {record:#x}')
        size = int.from_bytes(raw[12:], 'big')
        if size <= 0 or offset + size > len(disk):
            raise ValueError(f'{name}: file outside the disk')
        entries.append((name, offset, size))
        offset += size
    raise ValueError('Disk directory has no end marker')


def repack(disk: bytes, replacements: dict[str, bytes], additions: dict[str, bytes],
           limit: int) -> bytes:
    """Rewrite the directory and file area with replaced and added files."""
    entries = directory_entries(disk)
    names = [name for name, _, _ in entries]
    if replacements.keys() - set(names) or additions.keys() & set(names):
        raise ValueError('Invalid replacement or duplicate file')
    files = [(name, replacements.get(name, disk[offset:offset + size]))
             for name, offset, size in entries] + list(additions.items())
    if FIRST_RECORD + 16 * (len(files) + 1) > DIRECTORY_END:
        raise ValueError('Disk directory is full')
    end = PAYLOAD + sum(len(data) for _, data in files)
    if end > limit:
        raise ValueError(f'Files would end at {end:#x}, beyond {limit:#x}')
    result = bytearray(disk)
    result[FIRST_RECORD:DIRECTORY_END] = b'\xff' * (DIRECTORY_END - FIRST_RECORD)
    offset = PAYLOAD
    for index, (name, data) in enumerate(files):
        encoded = name.encode('ascii')
        if len(encoded) > 11 or not data:
            raise ValueError('Invalid file record')
        record = encoded + b'\0' + b'\xff' * (11 - len(encoded)) + struct.pack('>I', len(data))
        start = FIRST_RECORD + index * 16
        result[start:start + 16] = record
        result[offset:offset + len(data)] = data
        offset += len(data)
    if result[limit:] != disk[limit:] or result[:FIRST_RECORD] != disk[:FIRST_RECORD]:
        raise ValueError('Protected disk area would change')
    return bytes(result)


def jump(address: int) -> bytes:
    """JMP address.L followed by NOP: replaces exactly 8 bytes."""
    return b'\x4e\xf9' + struct.pack('>I', address) + b'\x4e\x71'


def hook(code: bytearray, address: int, original: str, replacement: bytes) -> None:
    """Replace original instructions after checking they are the expected ones."""
    expected = bytes.fromhex(original)
    start = address - CODE_BASE
    if len(expected) != len(replacement) or code[start:start + len(expected)] != expected:
        raise ValueError(f'Unexpected game code at {address:#x}')
    code[start:start + len(expected)] = replacement


def patch(disk1: bytes, disk2: bytes) -> tuple[bytes, bytes]:
    bootstrap = embedded('bootstrap', BOOTSTRAP, BOOTSTRAP_SHA256)
    editor = embedded('editor', EDITOR, EDITOR_SHA256)
    if len(editor) >= EDITOR_LIMIT or BOOTSTRAP_BASE + len(bootstrap) > BOOTSTRAP_LIMIT:
        raise ValueError('Embedded editor code is too large')
    name, offset, size = next(e for e in directory_entries(disk1) if e[0] == 'Code')
    code = bytearray(disk1[offset:offset + size])
    if CODE_BASE + len(code) != BOOTSTRAP_BASE:
        raise ValueError('Unexpected size of the game program')
    # Reserve the editor's memory when the game sets up its file cache, and load
    # the editor after the level metadata, before the main menu starts.
    hook(code, 0x3916, 'd3f800082b4900f8', jump(BOOTSTRAP_RESERVE))
    hook(code, 0x548, '610037fe61002730', jump(BOOTSTRAP_LOAD_EDITOR))
    code.extend(bootstrap)
    return (repack(disk1, {'Code': bytes(code)}, {}, DISK1_PAYLOAD_LIMIT),
            repack(disk2, {}, {'Editor': editor}, len(disk2)))


def identify(paths: list[Path]) -> dict[int, bytes]:
    """Read both inputs and match them to disk 1 and disk 2 by hash."""
    by_hash = {digest: number for number, digest in INPUT_SHA256.items()}
    disks: dict[int, bytes] = {}
    for path in paths:
        data = path.read_bytes()
        number = by_hash.get(sha256(data)) if len(data) == DISK_SIZE else None
        if number is None:
            raise ValueError(f'{path}: not a supported Lemmings disk image '
                             '(SHA-256 does not match)')
        if number in disks:
            raise ValueError(f'{path}: disk {number} was given twice')
        disks[number] = data
    return disks


def write(path: Path, data: bytes, inputs: list[Path]) -> None:
    if path.is_symlink():
        raise ValueError(f'{path}: refusing to write through a symbolic link')
    if path.exists() and any(path.samefile(source) for source in inputs):
        raise ValueError(f'{path}: output would overwrite an input image')
    # Write a new file and move it into place, so an existing file (or a hard
    # link to an input) is replaced rather than modified.
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, suffix='.tmp', delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(data)
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=f'Lemmings in-game level editor V{VERSION} disk patcher.')
    parser.add_argument('disks', nargs=2, type=Path, metavar='DISK.adf',
                        help='the two original Lemmings disk images, in any order')
    parser.add_argument('-o', '--output', type=Path, default=Path('.'),
                        help='directory for the patched images (default: current directory)')
    args = parser.parse_args()
    try:
        disks = identify(args.disks)
        patched = patch(disks[1], disks[2])
        args.output.mkdir(parents=True, exist_ok=True)
        for number, data in zip((1, 2), patched):
            path = args.output / OUTPUT_NAMES[number]
            write(path, data, args.disks)
            print(f'{path}  SHA-256 {sha256(data)}')
    except (OSError, ValueError) as error:
        parser.exit(1, f'error: {error}\n')


if __name__ == '__main__':
    main()
