#!/usr/bin/env python3
# Lemmings In-Game Level Editor V1.2
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Patch Amiga Lemmings disk images with the in-game level editor.

Usage: python3 patch.py DISK1.adf DISK2.adf [-o OUTPUT_DIR]
       python3 patch.py DISK1.adf DISK2.adf --whdload INSTALL_DIR

The two input images may be given in any order; they are identified by their
SHA-256 hashes. Only the exact supported pair is accepted. The inputs are never
modified. Two new images are written to the output directory (default: the
current directory):

    Lemmings_Disk1-editor-patch.adf
    Lemmings_Disk2-editor-patch.adf

With --whdload, the WHDLoad install is written instead: Lemmings.slave,
Disk.1, Disk.2 (patched with the WHDLoad version of the editor) and the
Workbench icon Lemmings.info.

Requires only Python 3. The editor, the slave and the icon are embedded
below; they are generated from the sources in src/ and whdload/ by build.py.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import re
import struct
import sys
import tempfile
from pathlib import Path

# The supported Lemmings disk images, identified by their SHA-256 hashes.
DISK_SIZE = 901120
INPUT_SHA256 = {
    1: 'a4fdba69017f1a760bba3bb06c55f7e434226c498c9d22c1f627212b08d24f91',
    2: '1526000b96d196efecab9c63aa72c0ce6257649a4993141b00ead8738fd97a65',
}
OUTPUT_NAMES = {n: f'Lemmings_Disk{n}-editor-patch.adf' for n in (1, 2)}

# The game's own disk directory: 16-byte records at $400..$13FF (the first one
# is reserved), each a 12-byte name and a big-endian 32-bit length. File data
# starts at $1600 and is stored back to back in directory order.
DIRECTORY = 0x400
FIRST_RECORD = 0x410
DIRECTORY_END = 0x1400
PAYLOAD = 0x1600
# Disk 1 keeps its raw boot loader at $CA000; files must end before it.
DISK1_PAYLOAD_LIMIT = 0xCA000

# The main program file "Code" loads at $400. The bootstrap is appended to it
# and must end before BOOTSTRAP_LIMIT, where the editor's chip-memory status
# bitmap starts.
CODE_BASE = 0x400
BOOTSTRAP_BASE = 0x21B4C

# BEGIN GENERATED BY build.py - do not edit by hand
VERSION = '1.2'
VARIANTS = {
    'floppy': {'reserve': 0x21B4C, 'load_editor2': 0x21B68, 'load_editor': 0x21BD6, 'limit': 0x21D00},
    'whdload': {'reserve': 0x21B4C, 'load_editor2': 0x21B68, 'load_editor': 0x21BD6, 'limit': 0x21D00},
}
SHA256 = {
    'floppy bootstrap': 'e5f08a89a4afaf445223eb4ecf8889fd01a14ede518ff483a7e7c025d184f42c',
    'floppy Editor': 'aceeb5a74cebf9a761173de6293146b82d7fdeb5b8534cb7e8ea5c41d4eec651',
    'floppy Editor2': 'a580d3eeb7188ddd90c949578c2da3741f4a984d05ac77e5e45c88c62a16412f',
    'whdload bootstrap': '1163db9bf7ccac43dd551e6b53dc141e33bc5eec6c17a6442e29c122145cf7a1',
    'whdload Editor': 'cdd85dfd3becd07642f61093a3ff33aa069b8626ae795464907392a902cd42c2',
    'whdload Editor2': '3ad946d2e2c941c5e9319a3db1b783c57c5cd5f8440e56ea716e4627d140e1be',
    'Lemmings.slave': '160b9c9e6905477abe80ebc03aa5cc269050f2016ddb2eeeda9d28bfe3de0630',
    'Lemmings.info': '14697767109ae2781bf469a09f4dcd2da4cb23c9ed259f78b890f17a786b8e2a',
}
BLOBS = {
    'floppy bootstrap': (
        '0/gACAy4AAJAAAAIZQaT/AACAAArSQD4Tvg5Hkjn//hB+gC7ShBmVAy4AAJAAAAIZUpB'
        '+swiQ/kABYgAcP9yBSQ8bWFpbk64f7JKgGYuQfoAhSJtAPhD6XAAcgBOuH+ySoBmGCJt'
        'APhB6XAAQ+kluiABTrg5NEH6AGVQ0EzfH/9OuDxuSkBO+AUQTrg9SAy4AAJAAAAIZS5B'
        '+gBDShBnJkH6ACwibQD4Q+lwAHIATrgyhiJtAPhB6XAAIAFOuDk0IG0A+E6QTrgsfk74'
        'BVBFZGl0b3IARWRpdG9yMgAA'
    ),
    'floppy Editor': (
        'AAAWgwMvBDJDTWHQhDWGkqJI/Fn4BigRAcoJAAJgEFSACXQFQBC9DlCIEBYBKgDBegag'
        'VUg4wKKAXYFAtUZAoKVRkCgq0AUFIAKCgxkBQoDGQFCsICiJoouQmgUF5EaBQXkFoDFQ'
        'LEIJsCjRafAbAIwWnwGwOMFScCKCcJjhT6FaNAKnIDt5MG4KnYDHReJQG2ioAUooGGAU'
        'Mj4ntCKEBH4DQgHsmFcRAJEAJqDVQjaCFIRqAI1IO9AYAzQSLAMoKfwCCygkGSxoATv+'
        'GwWTKAeIWmLZBtAVBL8ghYSOoG+CQIzEF4JqMiID8ogFAU4AgYSYwgiC+BEQSBIAhZTh'
        'ZAX6H9H0QGFcyQpCxA6TJKAoIXACGkq+gOmV5xBPaA2oApOgAcRABGlAxRkgE3IrbCFk'
        'kBhN6MMEgQ7mMEHEnTMHQLxjgZWQCleoNsgWBnrD3ay1BIGEZoJBQoDcVIESAkCKMxgh'
        'f7MARSQGvQM2QcLhmYQgqTUUGFIGAuQDCSgGBTgBhbwoDYMqARVgMEIYGQHiMyghKFgU'
        'DRBpD1kH8ICbY3gINV0LUCXKBujfAIvAZdeAFiYB5lCBV+A5g+gIyFTBtBgmqSBAQLQi'
        'LM0B2AiYB5niBYOSBVFoAwQQuAxBgBkgUg6xoMC54YFwAB8AYBZgjgAQkC0WPECAUIAx'
        'UTF9g4kRuE2A3FQbwGECsgTrIGYsgMQGUAICoqUEKtGaCWyA2IogKsgO2AwTxHxV/6ho'
        'U7CFpAaeAYElBgrYNiU0VRwL4AgHkAJugMUAgS+gw4GMBGyUZmF0ABFEgGDgVSAoCrKE'
        'BysBxZtAoEPAX0QNgGmUAlC3aA3d8BgxvBRGmJAYc6A5xS4EKgjUqhSAQEBALGBFEnAx'
        'JQMEKwXMEQBBoAAkfzEAklSKJeIMDDTRDBcy5MAWM6c8QGmAAoEGKKUAyeZEhkWkjgBy'
        'gFS4AgFIgNGAxvgN9fAaUBOgwKN0CE7awNsZipBhExQyRrQGJAaooGEzBUzwYG2DeYKm'
        'LICM0QYHAygkBggH/0Bo4MkIMJUmYYgkRQMNNoNEzGECQFBsQBCXSgA5AQlUoAuTk9gt'
        'KAHkDAoQHA2Or7VCAHz4Amk6DgBBDOBYDZmiCn8aSIDYzAZQ7mQMQSgINwYDTB8FAQYA'
        'UiAwg0BmsZFOiwG+3QMJQgM++P+j81QKCAEBsqBgJ9Chkw0g4yLdA0lC95JBNqDcgKoD'
        'p1KAnWjkFoYYBhkDlAHArQGSQRAg0+EI4KkEEDgGBqxohT2GQKBpFAfkCQrMsME9gUhA'
        'q3KAUDxhDMP6AAo4FRILBgc8BwEVAplMBUAHsWlGgFUuEZQJbAB/gb6Bn4AYQQugBIWB'
        'zgVgcTpwWg4Wr+A2cSgpikAYugCigShEg6wIknoBwVQ8xQEgC4KBRgEgUQgFwMpgljgC'
        '0iAzycVIIZiRSoMDzNEFS+B8wRA0ugfMIISCufAEFoKUBCKEeC0IiAgvhKgOmgMlACHQ'
        'PUSoC0oDfFJ0QwQg6QfbUmYfgQCBARL/ejCew4yQUmKAxCgVVCz5DpJk5Birk1LoCGKI'
        'ZndA6UagAERTxAYyBz2gbAEziEAEjYwMNAYhBOE2IDDwHpJOEgmFknIJAVKSEzCmBCB4'
        'OAYMhTk0Bg4GQQgrIUVAyRlChRCFIGZJS2ADOjVSh9DAoQAgmTBJkRTAIKBspwAvaA16'
        'nD6BJD0vcCmBEVEFUTOAdK9AbpL8AMBIgwihUgQQkhQGwoGKAFBKypRNDXmMCIIUCQGI'
        'yiwN8wwSoF8aB0eqLWiBEBBeA0coCAzfARIgGCOMsDJMNEMVYGeGhJyymKBxMxzH2uLN'
        'nA08IIqAYAwMaFKwm1CdNVMQAZ8R9lIC5lpkEh7A4eNZkw0UsN5oDaNeWQwJsAGKE4Fd'
        'JELw5DQgUlBiwOPBAOCBEG7Q+tAIUrBnhMAGKCbIAH0g0+IPqWMgceRh+vAeHqQtbrs4'
        'HKIDN0pRShFK4mEotyUbIII7E0DTZHDUwB/vCp9Gn1wgvgb9uAxSJACgMDxJihQKB0Fq'
        'woV4FRBAQoFA8wAhQYJCIXeChPzVARYChDzVATbEP0OLcm0BhzlXQWCgqtHmB+oQyRLf'
        'AdEvoAjgeCgb9QQHR8gDpWMSBkAEQT8Kgmld+LXQAEjEqA0cA8DAygtoAISVhoKUgFAo'
        'GelDAChQNKAkJAvwFwKBpBXERABQJsBwigZmUMAUFQwFAgIUDFAkGKgKBIgCIUDKAEGq'
        'gKBDAGoUDSyhk5BQqM1gMCcUU+iyrNhg+FlAEeAD74oJlJ2QGpAEwoGHf8AQo4UKKUCV'
        '2gOAgIHUcCoAOJguYBwUaAOBQM4CgZbHAmADiYLmAcFWgHBfgBgUlhgL3IDHhYAD0wXM'
        'kQHhOgHBbgAgcFZBSQiCwLJMFzHEGQXoDIVEAIMggAdqIFI0NAbpWgAwU0IgcCGmkGC5'
        'jSYQ2X0BsKSAMGygAWCgL+pGiFw8Bhg959AZgwrMKA2oKBsHIDRg02QwXMKQYRQGTcU+'
        'g9uQAHEJ2oDUgJmKKJfAFPjJCgrEMlBWBQreDIEMgEE1IGDgZ6jepmJACC6KA0ZUAD7A'
        'h7lh2yA6CGVAoiinP/LwDrXID/wPFhAbJGAwUgNWXnpCmB5gSBinkEiDijNg45J3IDDw'
        'NFYDAwMNQ4DjMAagQn7GQA4ECaOuoD5wA4oDdDQLA0TSDCBnEksDTuBIGcKXAArQ5FSA'
        'x8AIKA8Byri+A/6aEcgIRAACTQgnCJ6QGAAMKoaDgThQGj3EBd0B+H/AUnAaBU1dAfbq'
        'A2bydgRirjY2GgDhQRDKw4GWg4O2toXNzZ0AUDBhVyibQ2MicBQc0CYSHeTgfIGDIQoG'
        '4U8HQBgUGVewIggrABoO1rJCh1UETE3pRJ0NnUwBzwOB/cbAKAcGhJ1dnCxMYHB2Us7V'
        'xcS2oAJBqpaZmLvRKluYWLgD8UFS0DiaSst4DdiaA8Dgw6mxpaGNqRAGD6CwAODwJQmI'
        '2lg7DiViskUB11tAikr29rbEADY8CULKhm6mxAWBLgIZe0MTUgArGCURNLF3snAjVGOi'
        'YCI08CFQh2AQQSppa29namdgD/QMDgCpYqABCxC4AqHwoITLwKHCgeCCYWOZA6GQYJBQ'
        'YUtJ5B+C6Aq1ZG1pqBqADU4VEFApxMAWWLDVgAoG1F6IcLzjkVEwiVEwIICpdoR+sQIO'
        'VAYFBI+EBAYHFSxuq6A15Z8cAssLgDCq32AXgrgTeyVlUBTxD6nisUMvBHsTxADguio6'
        'EVEGUYXAL9FOBaClQpZeAsYPwDAmIpUPREQTCmdiCkxkXCGCrgsOMYIQCAKjURsQ4rQL'
        'MVGQhgKqBQNwKQllCpFhDLKGwtZxQe+CCEAVwGgKbSQFA4gEOXYAwDDlcy4JfiAhDiEf'
        'DgiAnISyEALEQRlQArU4AXRgA4HOiIAfKAK4DkVRKhQYXCBBdoGvAHcViL8BHgwYhgoG'
        'xC/FqJ4AqFhowBUFQABgQEAghCkkFAwUJBgQMdi7QrFRBiuCsIMLUTgCUFingHBPALC8'
        'IcLAA4JoGIQEEAcLwCHCAxgC8AgIQYIcArBeApgIACwGoqFAAwwSgQKEQAEgKI8IBwwc'
        'XwgQoL4AwCIAwLAIIQBWAcCQCAgGMEFINEIAVT8Bi4CiVAqBQVUcoFBVQqg3WAXQgnWE'
        'FGAZ+sQIzDrR1YIIVQEGn0S+WYDbInECKL8pQRSjxoaIB49AdCpSbEh6g7KIQOFAxCJw'
        'oHSH0BcKB1gB8VerGIASKQjvCwAUICIcqkDcCgsEvojjhK9GarVyA4IB0FAxmWCnEQvB'
        'HLzBMl0i0gEi7gRShirAZKlIDEAMQcDRFKAoVJ2gbkAcKPyS/CYAoo5iRBbVRoYkgSSg'
        'NYwl/UJkyjEpA1bcBtMhtTYBFFA/gBHuAxAsTMAETUBg79/kgkQel05oCEyKVoABhFAX'
        'gwSTKisqJhgJQAwiKSKkG44DoIQAYFDYzjAT8wVUIEy0gMwZoB0oDDFSFNBoPSHiaBRE'
        '4DAvMQQDBeAGsCizAEBCw22AEJmoHSgMEA4RQGmoALM1HC4KNlQASD3AQFA3UDtJMGGk'
        'MWUAYG8hbEhOVAYSjQCeQG+ULJ3gXAGCmS9IGsKWAzPxGjiBjwGjiBpwFDsB8zAXQAMQ'
        'LdAbgJ2pIHM9J2QxCEaAhFgleDoLBzAiAyILWYgwYwSSm6A3xS4GZQIMVWzQGIEwYhYE'
        'nA7iwU/k94WYCTDwQAEniYSUgMYZmhCOyA0uUgTgTjyGSA1VADxmwOHqwNT1Ab+ACi7/'
        'bgDDkKYAYhgYTT3EBL1zOCpgLMCunoAAc95AZMgDwBOoC9wI6iTMCgg247ggkhyHUBl6'
        'Vg5QCDKYIgMQCgdb68SkB6KMAFhbQD9IDNgDcmACoGBuwAoqm2A29wCrcA1KMEczBXh8'
        'AggAsoTB+9AJEsA4cgop0AgE4W3KA5YDbgAsyJkBkoLUCtAdF/kl/4TFKggPMDFkEA8J'
        'sFG6AmfuQG44S+CJD8APi5KNUpxAAZ88HWpGASygN6yuJECzwYXBgMoAPA43fk4BIIoQ'
        'GwAIQFCDBBYmo3geRNcAHAEFADGDnEmcCTKB3gkDiAuABCC0IsQsQQjqSWhFwAxFs8dg'
        'biDxXn/ppHyOogjeXBIgBUoD/wEEpD0Ei0lyAxKjVBBnhpUhQAtmYg4KqgN7AJFMWtyH'
        '6xQoX1ygPBZEDF1CAKihAMkQGhAIkQG6tCLSDRdQBMAWDWTgqGBBIOiAiQUA8kwLDFka'
        'IuFH0KBlSAxGoEOA5A2gISgJQapvQOYl8MlIapEGBgVSwHQuGEhIgMOIAyZGhFiziA19'
        'CgHSiiAgSY4GoR1E0MDNwVE+KgOAAPQuxA30BSzA2aIQLxR2IrKAA1DgVghmpAwIUB0B'
        'gYwCQdCsTMEIZBfALQjgHkGBroCQGBrcwbIEIon4AfUMgkc99gMQGGZgmOKhgaAxBK4n'
        '3ClOAyeGhGRgA8leKINA6UgNmIIFgpMNAOjQDvXA9hUgRT3BoCIvezQ1bQGrJwNwuIZD'
        'ZFAHCZZMADdYDhgTkmgSJwnFtBu0ji86gOGBVIB5gaihJK4D5gYkchsEwu+zKiDi1weC'
        'a0aADAJSidHoDZnQwFU4ga6A1MkBkgFQewDQAgwINPUNSoDP+ZwQVVgNgankgOglQBoW'
        'A3utgeAyK+EQAEsDKlIC1jAhJP8oDJCgQM7iDoRrloASFYIyiSW4kjiDqKAW2Ax7iBnA'
        'hOIM5i4gYGGmiC0TCYAkOs1RdQwFHEBoPUD9BAO/wLnAD7gAIDqQjQpoGIeYoguFb8QG'
        'GAfA4GRT5MX2CfTkRBKDcz4hgGG5oMBQfmHEBww/MmKQBrMglzgQCgdBlpANNKJlSgaG'
        'AkvBNg0VSBmpgB/FIEukBlkn0wR0LMiA0ySAMsrWUDSoi6ICYJsAdu/PKbApkkFUAwST'
        'VNAk1SABE9AwMNhnDmwTCgMzRAbAAKsBigYTAJFzECAIcICXIQASRiWFSgllSAM7YDJj'
        'CD6JDzMAVhHnFKgHQEBkngqaBQOpCAAzMALSuNRkDjFA79KTELYlgCmfqmQAiYJWHIFh'
        'QYDHWyAESVBQRBZABAmjfJmUEnAQKs0JwADJFHgXIC/JYGiU1CpiBMQMqC4CCBAJKhkr'
        'gBgchmgxR814LQAeBVVJC5gQhKLEzFEMTEFBKAIFRQphaQFBMYaDPCgDmFaQGVjzIUMh'
        'YA2wGzGgIIYPqYARtFCp4BQSacg63+AKaFgHFeEgYQhDCANoMCci2YgZVnQAloe4MiEj'
        'wCRAJT3sBgVlASsQRInRIgMCPxA5d0gj8wMDA6SYAQKas8kWThD2uVVnUsBwkDPKrAbA'
        'yq4BsHKogBFHAYhUOIoDAjgEShpmGC1BEOMAz6YEzYHORGAQQO8gbD5LFVANmRNgjFBA'
        'PbYDAwHzIDSwJNQAtgMITTZAhHF/gkAeVEC5LQBplmzxWSmIbBlKQSYAXFE5kZDMFA0Q'
        'YJmaFKC5jZh1PhUIMg+QEDAzpNgjlKgHAgSM5QWDArIBuFl5mBBzWA6VhCAzFNMFaigN'
        'MAhC/IxohILEAIQAJUBRlKqCcAQqsrRmyoLWMDAYpNCgPinQBliA28Bv1AyupSI3MQGA'
        'ajmJEMAtnMIIRBouZAQhReUouYCHSA1+TNmAL9eIrW+IQDRnQ2A8VEDYEwiAtAbBGFzF'
        'JAITFCAvAATsB8wJKAALVDAZJGAvlGhHCQOinAYCwGoJAGhok0ADWA0+Yg+3KmnyPqJg'
        'B/e0KYovwMnyiHQpTV0KmpBohumAUDmSE3BGyAxCXzFNPMMUTR+nuVdhIHkAkBQMsxAa'
        'QUhAyQhHQGOwGfVBAAiDIWZOAYXA4QaRS2QGnARWq4DwSoedogYVNAgwCeJO9q5mODAV'
        'diaMAODqEzJCEgokwNINFeYBxEgFynwcGVcH9YDOJJwIwjAEoqsBeriQUwA1gggqUMEd'
        'BnRDAKAA6miUJiDsFAxiRwAxSAxacCkIlBATYLAmiPowOiA93iBcEeAMBoMWKUCZAKBC'
        'AIgUDL5MNIGUHywgZSgikDEGBQQ/0EELgvgHUBBngJ9IbgoG2CIBRuAGZHAUMBqImB+A'
        'QZaBFpAZOmBE5h1lMDhMBAjySVBUDg4HYPcDISwAFM6hBMigYgaQaR0wDmIDFxCC5Mo8'
        'Bh5Af6Iwi6CdSeZomMCaIDAAGBTmGZpjAGIAB4KVACIUL4LFXp0HwSADhD6bA6pB0mED'
        'ogC7Bon9sg0CEgaA4HUO0GgXkAoIYBQqBeg/yUCvis0S+IEpDkTrEBpwGeIMQGlQEwgy'
        'vEGh+QgRAOUAhp6yAtypgOchYFBmpAZ8GBiCCgg+HtOQF8oCAuqcygXFKgJoQ53MXACB'
        'ecJIKYBkGSCJmJEwAUIKjRIZ/AUkgMCEGchMzAm4HMCAxgAdogKZhhNPMC1zJCUBBp9A'
        'PlMxpSFgc+nApj0O/yNUuAFkpTKAngFASqEYaGRiAyoV5+gEJQjYEoKBoglBEqD+QpnB'
        'QV9PgAFZhR+AMJfqClO4ASb4OkCf4QuAAiYeQF4kHqB1qapGDKI/BC6EWYJIWwTgwRiq'
        'w0F+bgJAsgFWJ2GC50UAIZETGCkAsxQhGjOqURjmYQUuLmo93EDKIc/kSaIXIB1/P8EU'
        'qNKQFzHTUBZB+Af4AgcoLOgKAcG8FcLgAwFCAoGsBQMnk74gJ3AQUQnACgwIQPAdWHAT'
        '4B+xYAVoKkQdTFKQYHEg6kgoY56gYC1f4A8XACZKQGLEB8ypBiLBL5ATYVKs0UDNZawJ'
        'CIDMC5wboAgdDAwQBEHAwEBBEPRREMPAT/Qhlj+UHRAcABQigb4AsgAA1cwxBPRAagzM'
        'CVBFnADO5bAdohQmF4ZQSkIGRwDk8cDfwcNQ4DjMAagQn7GQEDUEg2B5xKiX9hRKwNEt'
        'gALqpFDP4AGy4MqQktD8PqQIpMkkvcAQMFwB2CwOZAKMdkQANpiBRwA0IPFrgBpFWf+z'
        '4UvCACVwcQqQUyWhouD+g0FDQAOBG4ALuSGCYpTwOtSINgBEKHgAGegBBy/yQAch0YRm'
        'EEG0OMpCA2olIB4OSGOoGnACGUX0CgJ+BkigbkPeB5KVCcQU+iJrNhgKFDviC5RQn/n+'
        'FeCirM4C/gQZ+AEFTKAha4ZNQklIBIgMosQcGBeAiCQLMkC6gQQEGQgfBNgEwgoA4qdA'
        'QHJFBQYa+QRhcz7/Dz4mNcAWxBuAwSZUTkBLYqJkGm0BKZmCA5X/GIGEAFJdAYOI2Bga'
        '8lMR7gCgimM1I2I2TMEJwgXcFECpgOsByE6AbFMpAgoNxXGSBUQNEXQwAg/QMgWRiFnw'
        'B4C4kzIAdABeB2GUmFgYG+IUQnJBGcKBg1QIXAH5KAqoDgZHmgQVEwGIr4H68P+D8UHA'
        '8JC5KkAFnHmCFICZlBj0OWB6KDHWUBFgAlAXFIU4DBCF/3+RLYgL/f8qRw6BwMjAIRQA'
        'Mocyi0PFAKwBFoZYKACANQHK7wCBhDzBwJlCKQBxUn/l8ByAqQfwjYMQILAigEQSFIG2'
        'Y/IVWBwQKgEGVACJ/DICMyReFA4CRgICtJ0gPIBGgQcByIqHACCIeWIg030BQi4ggxlQ'
        'gwAAMEgKDeAOAigDwKBgpSAQAAKJ3DOiHUKBpk4CiAbCqEzTMBQLQBsHQpSLBsQWBNwF'
        'IUDJoeAYGwcDL5KiIUsIgYQinACDAaBmYEGA7oMoBuBiYGY0SDQAiYI3AHMIPQAiYO4C'
        'xAEAlngAGREEAIEQfAFBxuwEIUACBOsGAkUC4gbBeANlKCQAegxyJc4+AwHKBBgBFfni'
        'dwFyA3QA8AQHcIAY4OAoVkFwA3EEEv0DLDAB+NGX3AfDlXQCQYcgsDW8P/wI8BewKnAB'
        'cD9wBvAjyBwIPQg4SBNiOmlNrygiIAXASkxdkx1MBYKLDmzwJ4CBSB2WyMIEcoHtlBQO'
        '0tABF2lAwS9gVsUDOAEGEYINOhsZGTADlDvHoKbxINcA/z7AuJV7URdHA5gOB2OID9k7'
        'WQEJIPyRgcBHQMD38oHlQTVRAhDor0FI2WI7axAfcCjQQbZfIlIcDQ68NnUycXYgqisr'
        'KScuLKZM0llaQImELRLvZQRAoIMfk2BpywdDgNU2Fr5QP0DgaUJdU1tbIyphLmBg0QFA'
        'zRQhMA4MqQYfUMk7QiUQHDG0svUxCocCzgViaDKqCAECRQRVBAnk5AkkVAnVJGRkCIVE'
        'CGXllFTh3VDh2qaD5SugcDybMA4dEgg/UDB/gIqxCqNc4D0UWhb2NkKoUDUWhxtDY2Eg'
        'NBiwMDCAUGAAiUQHBC5hwP8UFAqxthwPqqGLoZOLsSop3tbAmIWtDc0tA+r6ey9oNHEB'
        'gZDLbJwLqQeWYKB3DTSaWPB9IMD3qlwIMJB/IUD7gbk9FbBxdPY8wsG+QRZFV2cBZAQe'
        'gK9USgQdqEg3yEpBCgeiDA/amgRF7xGL1gQFEUUm4GJUQUD9g6CJQwPWM78qxCzV2cjQ'
        'LhQ0C+psB2BgacBIuwsbdBdMZm0C0VaSYEg4OtQNSVOpoZDYPMW4HXKRT0VQCgdwEgzk'
        'VOTJgrQOTvbGBYwFMZ4tULpawILIDRxhaBpGVsFTgHkhUMAQhq6k6WROTzAjNDY3KZKJ'
        'VVcQUDhgZlqFUPaGBN1KWMPsCyLIU8CqqYCYAQ6IJB6gUDKgNlWljAYGUSZDlbQ3MhsF'
        'QA2B4NcH4jQEhCTJFwtAMtW/C90NnISRLlCuDiaGpyRM6AiAiRq6WNsTlaQIKJUo6AFB'
        'QuUAqEUBEa4Ze0MTEMIgFcIoO0MQIKUuSTsTUw8wYCgdEPSxdgUAQedDNyLwBBo0Njaw'
        'BNUkKeps5CoLkDQnb2hEAEMASqYurk52YED7OxdLO1dTMgIEAYBoOizsZcBMaGdsarGw'
        'Bgfd8LgwAAAlug=='
    ),
    'floppy Editor2': (
        'AAAABuI+B3AQY2BIigZoACTEAMP+ybEUkoKmIDukw/QYQkWA14D2iAwQ8hACqgRSiACA'
        'fGHgT8CBK8SSQIwBlBDiSdoJNEEQCIAcHRAoGESJB5oCXcFGCJBP0KZRAMKkW4ALv5EG'
        'ASARxEQ5FVEAcSCw0Q1IwPKh5YDQlWGRUmEAFmFLoAAyKRYeIGwPQHB2JEB5CIQCUEgg'
        'Ipy6oEDAVQgYGxWSAx5FH0UPBAYJsA8DjYrYnBmRAaVRLqHkaYHDLSkQc2PaPVRVDgAi'
        'ulA/gBdDAzSSgVSZUMEfAoFbABGRQTumweKoAAIScQgEYEF1NABUEtuDXgB0PIDwA1Ub'
        'AwK+mA0gwEvjbMmACW8YBRFI4DYqEQYPBLAJEQ0A73YUOU0HuSQShkFZIDeJQm9sBqA4'
        'DhxkNYGYiQIYQA4lgoKTP0B8UBhkESgMDPoc1zB0FtkB6CMrMiQCKjJ2LJj4YJLIDEC7'
        'gBMOwsxVAcEbgYNwUaNDLTIAMjkCEEOIwHKLrAy7+BAhEFOMkpFjcHNwcMRZCg5iANyW'
        'YEZAMaEcDkuIDB1LBZiiQo4IXQIDmEAf4Eun3B/sCGQGDsgNMA9FeQPRUuOBggwiDAHw'
        'ofCFgIDA4Hcg4HICkAGG1SDT1AyIUwkBkyJBim+ogKwBpBgbAARmYQUAdK2BOlwAPVbG'
        'qdUDTe0GILcBZEB9QkwDCenSAR3QWI+BmFnUoGBTIEYEKAuClBQKhABxXVKDQUMAiCqg'
        'PW4GyCuKUDAqwCSSDwWoCwMhOGFBYhEAqFA1tqBn4lClBEKXwUFSdouD8VDaCgCBOwD4'
        'UDVRL1KBkVLooOUTSTzOlEv9ZEx3qgbcADwA28VDWCEgNQ53MzICURNSilYTbAcrbAYu'
        'OwUIEJoBXIDOhPgSENQgABYHhQlkAiSDUinCWBSDxUZagZIIfFwOmoG3AKShYg4CrpB5'
        'UAixATBM4uCYVBa/szYSCQJwAZ+AfcqJPAALDRTC3A4qB4gHtYOCAoyyBE5gdPJcMcIY'
        'mQG5cwMQLDAjJqAYj/gPGEGHsgkgEa9BQM+pAYxmRUYfFUiwsFnAVCTANpwACBtUqALx'
        'QMYokAMEbEKAH9TEACfAgAAcS6gSnBh4NvsNTYmeGEhofM9qTCzMmEvtYQAchaga3FAw'
        '8TkAc0E0oZMwctXWQGvgFcQGPgBLwA1E4NNIQZAA9qcNgjFgNsIgYGmHlB/Zoi1cKcQG'
        'ZfeAgYTYNPYQEPxMAQlUDxP00CiqRQgQE5AIDOc0BCKVKARBgBATEDaJszQI5RLQAM8O'
        'EUC4CICBczgSHhGCnEJNPcFlegTMjFtqABbMdFE5gcWKRgIBLTyAxMxlZIMb7DwBqAJg'
        'CYpUpBQ1ZghpEBjwGCGBXpx2ADgAPmNKIDDkKCUKEA9m8AnVWQNwrgDwWtSdEMEIAC5A'
        'pmHw5CrX/AgyPHAz6R4kGWHnwBYWBoAF0UDDoCCYKypQLqkwDIRcQgtVSCsgGQOBigcD'
        'ZhCDKHAxAWoBoDAwYDyDA5KygAkkABAEqYAKBbAL4h4BSqEBWEMAGl1osAZCfh0BRqkB'
        'kEi9JBBNVgLUgEHapFIgD8iESBQbZAIZAdiA0T6gMC8AhsAFyIeMyKsf4NcxFICQGZgL'
        'WgwEyDQLMq04BQTJsAEfSLgAoNOOk0oXMCYXIwCgalhKyhh4kaeCkWFlYWHQQUAwiA18'
        'BeKCjiUxi0v4AzBAhJQ6qx5hCADIkAlDDyAeIYAo4YgMyAwSCAbEcCgdpJAAJgsCgZAV'
        'dmSLDx8AcH8PEgP4ZkiGBCFUuAdAQxlFKf+bhx+DIEM4MHGg0GsTHBUxl5giDAKcB2kS'
        'o5mEA4AIQDfgIIOAESITsBAKBiAGIUwYmjAKBU0DAPMvpDpgRsoCZk/BzegBBggIFJEg'
        'GSQROQLEkk/ZB+hplgLOgYBV6fA9UWABU/jgsFDvEKAhE0CPAaL+AINAMDebyCgIAAIK'
        'vACKrggGBtIYaICIDPoGkAnwCAXgEALIFzgB9wAFB1WSwBANEhGgAHMX2ITgAwAH6DwD'
        'B1ASAQdABAAGjq4QVAFG4AAgnwwzDgeEv4B0ncAIxhh+LAGAj40Ip1AQSkUAEFYrAX4H'
        'dIICkNMwxQ7KWhQM8EeAeRbHcHAXi74H4KBwwbBTFuAPBQMWv8RgSSdcIUzgTqrBYPHP'
        'A1VwOTMhQKhfrybIP1eAYpGALsQUPJJAxh8igalBMyIDDAafcRImWE1HTBKMUJUYRgjC'
        'MgmRJIwHW0/9zQ6hQPy9wAewGFOgoGSCUEr4V4clywF1O/8OApYHAQQEUg4CTjxipI5H'
        'SAQAeUbpeDgYEBIglg6H/UplmMCHRQQBGIAAajAAdQ71AOEgBBRHrOUgIDkhyKD5QEB4'
        'EJgA40W1VaBYoFVgaGGV0AjIonACCAKBw8ikLAbAswxxRhgZOBRhgYgBRquSvUHuAAOA'
        'g0ACmAg1AUpSgoFbQA4v6lBoKKgWhdwA4MDGivylAwKkgaoolZAWlHril4E0lkJgOyqw'
        'A/AB9/0DoIyA08x2TMwJSA4QZqDUJUzMwUhzkcSSgINYuYkPADuAm4bBhEpAWhQM6lkA'
        'YCuAMIMYINl/gfyugH6EOCHVcxBBjKWcZYggkiCgfwwnYBINkEKpQDgWrRg+lk6mCYMU'
        'lCiAZLmEINAcDcIoGJc/8/yS/TKiASFCNgBhIoS+nKSFAoeBoF4UoNBUcDpBbhloaSoI'
        'UDeVKBgUzAmTKLIFAwMAiJuARCgb9AQKhBwFRRQFncACC1zeAUJsAKFwlkEkj6AIhT+W'
        'QQrWA8yiBgFAAwVQAZEHESgBalGCF+DNFOf+D4Yh/lIZZhYhEK+lcT6fEAamNcJBRGOW'
        'fonihwEgd84gWCpQUCiHouBQJUAQeKfVWYswhehlUS/5k1Wf0Qo2AUw8gDtMW4qT/z/A'
        '5AKSAQr8IUgFmaKNEPlYae4gL/H2ZQDm8GYA6fBkAO74YAPxAy+/5/cq4yorLKgmqiAO'
        'jkAgQECkJAAADQAAUQAIB8AAQAyGAu8Hs2cbTAAAC0A='
    ),
    'whdload bootstrap': (
        '0/gACAy4AAJAAAAIZQaT/AACAAArSQD4Tvg5Hkjn//hB+gC7ShBmVAy4AAJAAAAIZUpB'
        '+swiQ/kABYgAcP9yBSQ8bWFpbk64f7JKgGYuQfoAhSJtAPhD6XAAcgBOuH+ySoBmGCJt'
        'APhB6XAAQ+kkTCABTrg5NEH6AGVQ0EzfH/9OuDxuSkBO+AUQTrg9SAy4AAJAAAAIZS5B'
        '+gBDShBnJkH6ACwibQD4Q+lwAHIATrgyhiJtAPhB6XAAIAFOuDk0IG0A+E6QTrgsfk74'
        'BVBFZGl0b3IARWRpdG9yMgAA'
    ),
    'whdload Editor': (
        'AAAAALQYG2ghkhprDoQhrDSVEkfiz8AxQIgOUEgAEwCCpABLoCoAhehyhECAsAlQBgvQ'
        'NQKqQcYFFALsCgWqMgUFKoyBQVaAKCkAFBQYyAoUBjIChWEBRE0UXITQKC8iNAoLyC0B'
        'ioFiEE2BRotPgNgEYLT4DYHGCpOBFBOExwp9CtGgFTkB28mDcFTsBjovEoDbRUAKUUD1'
        'ECGR8T2hFCAj8BoQD2TCuIgEiAE1BqoRtBCkI1AEakHegMAZoJFgGUFP4BBZQSDJY0AJ'
        '3/DYLJlAPELTFsg2gKgl+QQsJHUDfBIEZiC8E1GREB+UQCgKcAQMJMYQRBfAiIJAkAQs'
        'pwsgL9D+j6IDCuZIUhYgdJklAUELgBDSVfQHTK84gntAbUAUnQAOIgAjSgYoyQCbkVth'
        'CySAwmVBKCQIdzGCDiTpmDoF4xwMrIBSvUG2QAAz1h7tZagkDCM0EgoUBuKkCJASBFGY'
        'wQv9mAIpIDXoGbIOApDMIIVJqKDCkDAXIBhJQDApwAwt4UBsGVAIqwGCEMDIDxGZQQlC'
        'wKBog0h6yD+EBNsbwEGq6FqBLlA5QdgEXgMuvACxMA8yhAq/AcwfQEZCpg2gwTVJAgIF'
        'oRFmaA7ARMA8zxAsHJAqi0AYIIXAYgwA0QBwdY0GBc8MC4AA+AMAswRwAISBaLHiBAKE'
        'AYqJi+wcSI3CbAbioN4DCBWQJ1kDMWQGIDKAEBUVKCFWjNBLZAbEUQFWQHbAYJ4j4pf9'
        'Q0KdhC0gNPAMCSgwVsGxKaKo4F8AQDyAE3QGKAQJfQYcDGAjZKMzC6AAiiQDBwKpAUBV'
        'lCA5WA4s2gUCHgL6IGwDTKAShbtAbu+AwY3gojTEgMOdAc4pcCFQRqVQpAICAgFjAiiT'
        'gYkoGCFYLmCIAg0AASP5iASSpFQvEGBhpohguZcmALGdOeIDTAAUCDFFKAZPMiQyLSRw'
        'A5QCpcAQCkQGjAY3wG+vgNKAnQYFG6BCdtYG2MxUgwiYoZI1oDEgNUUDCZgqZ4MDbBvM'
        'FTFkBGaIMDgZQSAwQDT6A0cGSEGEqTMMQSIoGGm0GiZjCBICg2IAhLpQAcgISqUAXJye'
        'wWlADyBgUIDgbHV9qhAD58ATSdBwAghnAsBszRBT+NJEBsZgModzIGIJQEG4MBpg+CgI'
        'MAKRAYQaAzWMinRYDfboGEoQGffH/R+aoFBACA2VAwE+hQyYaQcZFugaShe8kgm1BuQF'
        'UB06lBGpAYQFoYYBhkDlcArQGSQRAg0+EI4KkEEDgGBqxohT2GQKBpFAfkCQrMsME9gU'
        'hAq3KAUDxhDMP6AAo4FRILBgc8BwEVAplMBUAHsWlGgFUuEZQJbAB/gb6Bn4AYQQugBI'
        'WBzgVgcTpwWg4WF+A2cSgpikAYugCigShEg6wIknoBwVQ8xQEgC4KBRgEgUQgFwMpglj'
        'gC0iAzyClIIZiRSoMDzNECS+B8wRBkugfMIISCufAEFoKUBCKEeC0IiAgvhKgOmgMlAC'
        'HQNkKIC0oDfFJ0QwQg6QfbUmYfgQCBARL/ejCew4yQUmKAxCgVVCz5DpJk5Birk1LoCG'
        'KIZndA6UagAERTxAYyBz2gbAEziEAEjYwMNAYhBOE2IDDwHpJOEgmFknIJAVKSEzCmBC'
        'B4OAYMhWk0Bg4GQQgrIUVAyRlChRCFIGZJS2ADOjVSh9DAoQAgmTBJkRTAIKBspwADaA'
        '16nD6BJD0vcCmBEVEFUTOAdXdAbpL8AMBIgwihUgQQkhQGwoGKAFBKypRNDXmMCIIUCQ'
        'GIyiwN8wwSoF8aB0eqLWiBEBBeA0coCAzfARIgGCOMsDJMNEMVYGeGhJyymKBxMxzH2u'
        'LNnA08IIqAYAwMaFKwm1CdNVMQAZ8R9lIC5lpkEh7A4eNZkw0UsOJoDaNeWQwJsAGKE4'
        'FdJELw5DQgUlBiwOPBAOCBEG7Q+tAIUrBnhMAGKCbIAH0g0+IPqWMgceRhovAeHqQtbr'
        's4HKIDN0pRShFK4mEotyUbIII7E0DTZHDUwB/vCp9Gn1w5PgY9uAxSJACgMDxJihQKB0'
        'FqwoV4FRBAQoFA8wAhQYJCIXeChPzVARYChDzVATbEP0OLdS0BhzlXQWCgqtHmB+oQyR'
        'WfAdEvoAjgeCgb9QQHR8gDpWMSBkAEQT8Kgmld+LXQAEjEqA0cA8DAygtoAISVhoKUgF'
        'AoGelDAChQNKAkJAvwFwKBpBXERABQJsBwigZmUMAUFQwFAgIUDFAkGKgKBIgCIUDKAE'
        'GqgKBDAGoUDSyhk5BQqM1gMCcUU+iyrNhg+FlAEeAD74oJlJ2QGpAEwoGHf8AQo4UKKU'
        'CbWgOAgIHUcCoAOJguYBwUaAOBQM4CgZbHAmADiYLmAcFWgHBfgBgUlhgL3IDHhYAD0w'
        'XMkQHhOgHBbgAgcFZBSQiCwLJMFzHEGQXoDJbroDAAMggAdqIFIj1AbpWgAwU0IgcCGm'
        'kGC5jSYQ2X0BsKSAMGygAWCgL+pGiEvcBhg959AZgwrMKA2oKBsHIDRg02QwXMKQYRQG'
        'TcU+g9uQAHEKGoDUgJmKKJfAFPjJCgrEMlBWBQreDIEMgEBlIGDgZ6jepmJACC6KA0ZU'
        'AD7Ah7lh2yA6CGVAoiinP/LwDrXID/wPFhL8oSYYKQGrLz0hTA8wJAxTyCRBxRmwcck7'
        'kBh4GisBgYGGocBxmANQIT9jIAcCBNGLUB84lBL4o7hYGiaQYQM4klgadwJAzhS4AFeH'
        'IqQGPgBBQHgOVcXwH/TQjkBCIAASaEE4RPSAwABhVDQcBsKA0e4gQugPw/4PU4DQKiTo'
        'D8tQGzeTsCMVcbGw0AcKCIZWHAy0HB21tC5ubOgCgYMKuUTaGxkTgKDmgTCQ7ycD5AwZ'
        'CFA3Cng6AMCgyr2BEEFYANB2tZIUOqgiYm9KJOhs6mAOeBwP7jYBQDg0JOrs4WJjA4Oy'
        'lnauLiW1ABINVLTMxd6JUtzCxcAfigqWgcTSVCvAbsTQHgcGHU2NLQxtSIAwfQWABweB'
        'KExG0sHYcSsVqCgOutoEUle3tbYgAbHgShZUM3U2ICwJcBDL2hiakAFYwSiJpYu9k4Ea'
        'ox0TARGngQqEOwCCCVNLW3s7UzsAf6BgcAVLFQAIWIXAFQ+FBCZeBQ4UDwQTCxzIHQyD'
        'BIKDClpPIPwXQFWrI2tNQNQAanCogoFOJgCyxYasAFA2ovRDhecciomESomBBAVLtCP1'
        'iBByoDAoJHwgIDA4qWN1XQGvLPjgFlhcAYVW+wC8FcCb2SsqgKeIfU8Vihl4I9ieIAcF'
        '0VHQiogyjC4BfopwLQUqFLLwFjB+AYExFKh6IiCYUzsQUmMi4QwVcFhxjBCAQBUaiNiH'
        'FaBZioyEMBVQKBuBSEsoVIsIZZQ2FrOKD3wQQgCuA0BTaSAoHEAhy7AGAYcrmXBL8QEI'
        'cQj4cEQE5CWQgBYiCMqAFanAC6MAHA50RAD5QBXAciqJUKDC4QILtA14A7isRfgI8GDE'
        'MFA2IX4tRPAFQsNGAKgqAAMCAgEEIUkgoGChIMCBjsXaFYqIMVwVhBhaicASgsU8A4J4'
        'BYXhDhYAHBNAxCAggDheAQ4QGMAXgEBCDBDgFYLwFMBAAWA1FQoAGGCUCBQiAAkBRHhA'
        'OGDi+ECFBfAGARAGBYBBCAKwDgSAQEAxggpBohAC23gMXAUSoFQKCqjlAoKqFUG6wC6E'
        'E6wgowDP1iBGYdaOrBBCqAgy2iX3QHhqZE4gRRflKCKUeNDRAPHoDoVKTYkPUHZRCBwo'
        'GIROFA6Q+gLhQOsAPir1YxACRSEd4WAChARDlUgbgUFgl+4CsJXozVd2QHBAOgoGMywU'
        '4iF4I5eYJkukWkAkJXoDUoYqQGSGSAxADEHA0RSTEDU4DmQChXIA4Ufkl84UFIo5iQA5'
        'bVRoYkgBigNYwl9kZEyiPJAzcT8DTIbU2ARRQP4f4KGIDECxMwCXP/A79/kgkAcel05o'
        'CEyKVoABhFAXgwSUIfoDogGAlADCIpIqQIjgOghABgUNjOMBPzBVQgT5SAzBmgYSgMMV'
        'IU0Gg9IeJoFETgMC8xBAMF4AawKLMAQELDbYAQmahhKAwQDhFAaagAszUcLgo2VABIPc'
        'BAUDdQO0kwYaQxZQBgbyFsSHBUBhKNAU5Ab5QsneBcAYKYmUgawpYDM/EdWIGPAdWIGn'
        'ARWwHzMBdAAxDq0BuAnakgcz0nZDEIRoCEWCV4OgsHMCIDIgtZiDBjBJNVoDfFLgZlAg'
        'xVm1AYgTBiFgScDuLBT+T3hZgJMPBAASeJh6SAxhmaECq4DBFIE4E48hkgNVQA8wOuGg'
        'MABkBAjHSoDfwAUXf7cAYchTADEMDCae4gJeuZwVMBZgV09AADjXIDJkAeAJ1AXuBHUS'
        'ZgUEG3HcEEkO0KgMvSsHKAQZTBEBiAUDp3XiUgPRRgAsI8AJpAZsBHkwAVAwN2AFFcq6'
        'BpyA3AKtwDUIwRzMFeHwCCACyhWgB6QHSJYBw5BRToBAJwtuUHiwG3ABZkTIDJQWoFaA'
        '6L/JQOYvUoCA8wMWQQDwmwEOCZY5AYVhL6wVvwA+LhIMSnEABnzwdakZS4uZ6yuJECzw'
        'YXBgMoAPg6Xfk4BIIoQGwAIQFCDBBYmo3geRNcAHAEFADGDnEmcCTKB3gkDiAuABCC0I'
        'sQsQQjqSWhFwAw5s8dgziDxXn/ppHyaogmeXBIgNN/f8CCUh6CRaS5AYlRqgfUwNKQoA'
        'W1HuXJQG9gQimLW5D9YoUMa5QBADGRA9tQgIooQCeUIB3LE1OjWTgqGBBIOiX9BHweSY'
        'FhiyNEXCj4FyTZKqgZAJ9IgDwLx8gGwsMMlId+EGBgEiwHQuGEhIgMOIAyZGhFg5iA19'
        'Cg4SBCAgDI4GoV1IEMDNwVE1igOAAlSixA30DYzA6yZEKCeuAxoCvFEGgTKQGzEECwUk'
        'DpSAwQCfTA+OKgEU9waAiL3s0Pk0BqycDsGiGQ2RQBwmWTAB3WA4YE5JoEicJJbQbtI4'
        'pKoDhgVSAeYGooTDOA+YGJHIbBMLvsyog4jcSgmtGgAwCUogQ6A2Z0MBVOJK2gNzJAZI'
        'BUHUA0AIMCDT1ClKAz/mcIbHVIQGBreSA6CVAGhYDe6mH4DIr4RAv8wMqUgLWMCEknig'
        'MkKBAzuIOhGuWgBIVgjKJJbiSOIOooZBbKoE5iBnAhOIFCQH+g8B1AYaaMLRMJgCQ6zV'
        'F1DA6Z4AfNQP0EA7/AucAPuAAgOpCNCmgYh5iiC4VfxAYYB8DgZFPkxfYJ9OREEoNzPi'
        'GAYbmgwFB+YcQHDD8yYpAGsyCXOBAKB0GWkA00omVKBoYCS8E2DRVIGamAH80zgMsk+m'
        'COhZkQGmSQBllaygaVEXRATBNgDt355TYFMkgqgGCSapoEmqQAIjeGBpEM4IZ5XgGaID'
        'YABVgKUDCYBIuYgQBDhAS5CACSMSwqUEsqQAHrAZMYQfRIeZgCsI84pUA6AgMk8FTQKB'
        '1IQAGZgBaVxqkgcYoHflqYhbEsNIGMECZACJglYcgWFBgMdbIARJUFBEFkAECaN8mZQS'
        'cBAqzQnAAMkUeBcgL8lgaJTUKmIExAyoLgIIEAkqGSWAGByGaDFALWIr+B4FVUkLmBCE'
        'osTMUQxMQUEoAgVFC6DJAUExhoM8KAOZFJAZWPMhQyFhdrAbMaAghzEE0oGKF1wCgk05'
        'B1v8AU0LAOLtxAwhCGEEbQYE5FsxAyrOgBJQFwZEJHgEiAShrYDArKAlYgiROiRAYGti'
        'By7TBrZgYGB0kwAgU1Z5IsnCHtcqrOpYJuIGeVWA2BlVwDYOVRADT2AxCocRQGBHAIlD'
        'TMMFqCIcYAX0wJmwOciMAggd5A2HyWKqAbMibBGKCAS6wGBgDqQGlgSagurAYQmmyBCO'
        'L/BIE8qIFyQgDTLMNwABZKAhsGUouiAxcUTmRkMwUDRBgmZoUoLmNmHU+FQgyD5AQMDC'
        'k2COUqAcCBIzlBYMCsgG4WXmYENJYDpWEIDMU0wULyA0wCEL8jGiEgsQAhAAlQFGUqoI'
        'QBiqqtGbKgtYwMBillyA+KTAOhIDbwA7UDG6lI5cuAYBqOYkQwC2cwghEGi5kBCFD5Si'
        '5gNpIDf5M2YAv14itb6tAtGdDYDxRiJhEBWA2CMKWLSAQmKEBRAFDYD5gSUQAWolLAb+'
        'UaEcJB6KcAA6oJAGhok0BcWA0+Ygh3KmnyMaJgB/e0KYo/wMnyiEwozVMKypBohemAUD'
        'mSE3A7SA+YDhO6aeIUrmAB0gNyroMwg4EgegCQFA6CAAJBS4DJcENAQbAZ8LAACINggk'
        'YDSL+BpFDpAbTPIuYDwSoedegYVNAgwCeJO9q5mODAVdiaMAODqEzJCEgokwNINFeYBx'
        'EgFyX3wGVcG5YDcJvEoIwjAEoqsBeriQUwA1gggqUMG1BnRAhPeA6mikHCDsFAxiSwBS'
        'SAyacCkIkdi3gTRd4YHRAe4hAuCLAGA0GLFKBDAFAhAEQKBl8mGkDIugrQZSgikDEGBQ'
        'Q/0EEKFQOkHUBBowJ9IbgoG2CIBRuAGZHAX0ANImB+AQYaBJJAYOmBE5h1lMBcJejySV'
        'BEDgYHqyGAyEsABTO7QfSigAIGmGkdMDoiAxcQAMLCpEQYeQH+iDbDyreKTzNExh9kAA'
        'YFOYZmmMAYgAHgoUAIiRYgsVe1wfBIAOFPhEDqEMSYQOiALsGif0yDQICBoBgYRFIGgc'
        'kAoIYBQiBWgXiUCW1gbUS/wTKkAswBwiGE4ASMLkEpUBMYMrxBofkIEQDlAIbR2ncqYB'
        'HSsBAHhNgyDJGMHgvpJKHAMGapw2Ae0qAmhCVcwD+eZwkgpgGQZIImYkTEVNBAaILhSS'
        'AwIAFJCoIyaBbgQGMENAwDMMJuG6/+ZISgIgTQD5TMeD6ThwKY9Dv8hkLgBMlIAFiA+Z'
        'UgxFWpegKlWqKBsstYDBEBmBc4N0ARWhgYIAiDgYCAgiHooiGHgJ/oQyx/KtogOAAoRQ'
        'N8AWQAAauYYgbogNQZmBKgizgBnctgO0QoTC8MoJSEDI4B3uOBv4OGocBxmANQIT9jIC'
        'BqCQbA84lRL/QulYGiWwAF1Uihn8ADZcGVISWh+H1IEUmSSXuAIGC4A7BYHMgFGOyIAG'
        '0xA/YAaEHi1wA0irP/Z8KXhABK4OgVIKZLQ0XB/QaChoAHAjcAF3JDBMUp4HWpEGwAiF'
        'DwADPQAg5f5IAOQ6MIzCCVaHGUhCrVfARQB4OSAOoGnACAUX0CgLeAEigYkMeAZK5CcQ'
        'U+jRrNhgKFDviCpRQn/n+CeUilM4C/gPp+AP5WKXBa4ZNQYhQMgeIKAUDSBdQIICDIQP'
        'gpwCYQUAcVOgIDkigoNtfIIwuZ9/h58TGuALYg3AYJMqJyAlsVEyDTaAlMzBAcr/vEDC'
        'ACkugMHEbAwMBSmI9wBQRTGakbEbJmCE4QLuCiBUwHWA5CjANimUgQUG4rjJAqIGiLoY'
        'AQfoGQLIxCz4A8BcSZkAOgAvA7DKTCwMDfEKITkgjOFAwapQJQBrlAfUBwMjzQIK2YDQ'
        'QAD9eH/B+KDgeEhclSACzjzBCkBMygx6HLA9FBjrKAiwASgLikI8BghC/7/IlsQF/v+V'
        'I4dA4GRgEIoAGSOBxaHigFYAi0MsFABAGoDld4BAwh5g4EyhFIA4qT/y+A5AVIP4RsGI'
        'EFgXQCIJCkDbMfkKrA4IFQCDWgBE/tkBGZIvCgcBIwEBBk6QHkAjQLOA5EVDgBBEPLEQ'
        'ab6AoRcQQYyoQYAAGCQFB4gHAXQB4FAwUpALAAFFHhnRDqFA0ycB5ANhVCZpmAoFXJ0K'
        'UiwAkFgU8BSFAyaHgGBsHAy+SoiEbCIGEIpwAgwGgZmBBgO6DKAbgYmBmNEg0AImCNwB'
        'zCD0AImDuAsQBAJZ4ABkRBACBEHwBQcbsBCFAAgTrBgJFAlIGwXgDZSgkAHoMciXOPgM'
        'BygWYARX6EncBcgN0APAEB3CAGODgJsnZBcANxBBL9BqwwAfvRl9wHw5V0AkOHILA1vD'
        '/8CCF/YCzgUuAR4F3gN5BkEBYQGJB2qHTSm15QREALgJSYuyY6mAsFFhzZ4E8BApF7LZ'
        'GECOUD2ygoHaWgAhHSgYJewF2KBnACDqMEGnQ2MjJgByh3j0Fj4kGuAwEQH7AuL17UU9'
        'HA5gOBpOID9k7WRUJIMqRgcBHQMDACoHlQTVRAhDor0FIx0YIEhx3cBTQQbZXZVTEBwx'
        'tLL2OOsk7ZyN6LgQVRWVlJOXFlAhFJZWkCJlB50S72UEMKCDv5NgBc6HQ4G1NhB+UDEU'
        'EGsCLAwMsuYAjRAUDNFCCcjg8qdgDBpCaDvokGdUsA+lIcIEsLHHUSD9naCiiA85QMqa'
        '2tqB4531DgqRAai4UzfkHVNh2qaD5SugcDybMA4dEgg/UDB/gIqxCqNc4D0UWhb2NkKo'
        'UDUWhxtDY2EgNBiwMDCAUGAAiUQHBC5hwP8UFAqxthwPqqGLoZOLsSop3tbAmIWtDc0t'
        'A+r6ey9oNHEBgZDLbJwLqQeWYKB3DTSaWPB9IMD3qlwIMJB/IUD7gbk9FbBxdPY8wsG+'
        'QRZFV2cBZAQegK9USgQdqEg3yEpBCgeiDA/amgRF7xGL1gQFEUUm4GJUQUD9g6CJQwPW'
        'M78qxCzV2cjQLhQ0C+psB2BgacBIuwsbdBdMZm0C0VaSYEg4OtQNSVOpoZDYPMW4HXKR'
        'T0VQCgdwEgzkVOTJgrQOTvbGBYwFMZ4tULpawILIDRxhaBpGVsFTgHkhUMAQhq6k6WRO'
        'TzAjNDY3KZKJVVcQUDhgZlqFUPaGBN1KWMPsCyLIU8CqqYCYAQ6IJB6gUDKgNlWljAYG'
        'USZDlbQ3MhsFQA2B4NcH4jQEhCTJFwtAMtW/C90NnISRLlCuDiaGpyRM6AiAiRq6WNsT'
        'laQIKJUo6AFBQuUAqEUBEa4Ze0MTEMIgFcIoO0MQIKUuSTsTUw8wYCgdEPSxdgUAQedD'
        'NyLwBBo0NjawBNUkKeps5CoLkDQnb2hEAEMASqYurk52YED7OxdLO1dTMgIEAYBoOizs'
        'ZcBMaGdsamOwAAEHmWHuzwAAJEw='
    ),
    'whdload Editor2': (
        'AAAAA5AwNWAAiqgG6oGmgF6gpMiIYoyE7AICsAUBYQEQsABGChaQOwuwC6XAC9U1qYFQ'
        'MvrQfAcJp6AE6hJgGEDOkAjugamFyBgJ0pQMCuQIwIWhIVKCgUiA0CaKUGgqYBEFUA/l'
        'wNkEMUoGBTgEkkM4jIFgZCCAKttiEFUKBnFUDhgRcoKUEQreB+F3A/AINoAEC9gI4oGZ'
        'RA2KSDIpXRQcodUknmdKKhVEYAwqBtwAPADbxUdYISA00AOZmQEoialFKwm1g7RWAxcd'
        'goQITQCBOhFpGoQAAsDhiMEcgbioGRTkKsApKtlQNkEOi4PJYDKCkoCgSbCgUT0Aprgb'
        'EJMAmliAGCpADAYGnMw4SCQJwAZ+AfQqJPAALDRDBxA4EGAmVYMzltYgTVwPAKIJAqQG'
        'EkBuNMDECkci4MgIfo7lExwb9ggyADfS67B0xAZhFAwMDeXNEWpDeI/YAB8R6gJqiZcU'
        'kBssxYpFHMGUYBnOZUUrQnDFs8ibMzx6aEM8Mn0zNDUATFBxGfgKYhyFAxFCAgiHAeAY'
        'HxL82ndZ/QUHosnqEiIyIrRIA0iANAEAQ/4DyUtSARMwpBoEOAsCSAWBQALEGnsHCrMk'
        'QJaAWoGEUDRIwhgdBagCCpoJ+BIKGALhAwFwnJYsDgQQhNFOAUAabJggKZhBSQVUdzIA'
        'dguqLgSBJAMhfSQgqCbQzChSnoXCGXUEhUQbgSFfAYG31DwDYpyIJIAhQoYZ9BAjNUH9'
        'AaCgacAJiHmQUM/QwQsNrCxW1E+kKwjgB2vggQTEoGrIgMjAQSDQ0MyQANBUQBRJ2AQQ'
        'AoGhDOVAsxeCMLBGRLwDIzYHcuELwf5MAwSkHoB/tUjRRLBC/+DwxOiXADY2AGAQS+AO'
        'SJrAAg5KpB2C6D6BHiAzAA/LAAFSgfoDNucAPuAAIByWAIBokI0AA5i+xCcAGAA/QeAY'
        'OoCQCDoAIAA0dXCCoAo3AAEE+GL2IDpra2lnbmzvrKhm6mIpbO1nSGJmYAMOVBQPCX8A'
        '6TuAEYww/FgDAR8aEU6gIJSKACCsVgL8DukEBSGmYYodlLQEG2gPItjuDgLxd8D8FA4Y'
        'Ngpi3AHgoGLX+IwJJOuEKZwJ1VgcGvBqqgcmZCgVC/Xk2Qfq8AxSMAXYgoeSSBjD5FA1'
        'KCZkQGGA0+4iRMsJqOmCUYoSowjBGEZBMiSRgOtp/7mh1Cgfl7gA9gMKdBQMkEoJXwrw'
        '5LlgLqd/4cBCAOAggIpBwEnHjFSF0CkAgA8o3S8HAwICRBLB0P+pTLMYEOiggCMQAA1G'
        'AA6ZzmAcJACCiPWcpAQHJDkUHygIDwITABxEpq4CxQKrA0MMroBGRROAEEAUDh5FIWA2'
        'BZhjijDAycCjDAxACjVcleoPcAAcBBoAFMBBjwsKlBQK2gaBdFKDQUVwoMkaABwYGslT'
        'FKBgVJA1RRKyAtKPXFLwJqtbBA7KrAD8AH3/QOgjIDTzHZMzAlIDhBmoNQlTMzBSHORx'
        'JKAg1i5iQ8AO4V9AIGEUvLgWlESrYDAVwBhBjBBsv84gdC6AfoQ4IdVzEEGMpZxliCCS'
        'IKB/DCdgEg2QjGajgWrRg+lk6mCYMUlCXAZLmEINAcDcIoGJc/8/yS/TKiASFCNgBhIi'
        'iyqUFAoeBoFyUoNBUcDoJllwaSoIpgpSlAwKZgTJlE2UoMhQOigYSoARCgb9AQKqreIF'
        'RRQFncACC9z2CKIIAKFwlkEkj6AIhT+WQQrWA8yiBgFAAwVQAZEHESgBalGCF+DNFOf+'
        'D4Yh/lIZZhYhEK+lcT6fEAamNcJBRKeWfonihwBA8ELAWCpQUCibYuBQJUAQeJfe2Ysw'
        'hehlUS+VotWf0Qo2AUw8gDtMW4qT/z/A5AKSAQr8IUgFmaKNFvgYae4gL/H2ZQDm8GYA'
        '6fBkAO74YAP1oy+/5/cq4yorLKgmqiAOjkAgQECkJAAADQAAUQAIB8AAQAyGAu8Hf0Ff'
        'ogAAB3A='
    ),
    'Lemmings.slave': (
        'AAAD8wAAAAAAAAABAAAAAAAAAAAAAACTAAAD6QAAAJNw/051V0hETE9BRFMAChAGAAgA'
        'AAAAAAAAfgAAAAAAWQAVwAAAKgAzAE9MZW1taW5ncwAxOTkxIERNQSBEZXNpZ24gLyBQ'
        'c3lnbm9zaXMASW4tR2FtZSBMZXZlbCBFZGl0b3IgVjEuMgpieSBUaW1vIEhlaW1vbmVu'
        'AAAAAABD+v/6IogkSCA8AAAEACI8AAAQAHQBQfkABwAATqoAKEP5AAcAECY8AAAWAAyR'
        '/////2cAAMoMkUNvZGVmBkopAARnCtapAAxD6QAQYN4iKQAMsrwAAhgqZgAApCADdAFB'
        '+QAABABOqgAoQfoAniAYZwwiQCAYsJFmAACEYPBB+gC2M/xO+QAAgNYjyAAAgNhB+gD2'
        'M/xO+QAAgWQjyAAAgWYz/E51AACEHDP8TnUAAIQ4QfoA9jP8TrkAABdaI8gAABdcM/xO'
        'cQAAF2AgOv7UIcAABCH8AAf/8AAIIEDR/AAH//Ag/FdIREwgykPoAAggyUKQTqoAIE75'
        'AAAEAEh4AAkvOv74WJdOdQAAgNZKQGsAAACBZFD5AAAAAIQcCLkABwAAhDgI+QAHAAAX'
        'Wgj5AAYAAAAASOfg4HABtLxtYWluZxpwArS8R3JvdWcQcAAQLQACVUCwfAABZwJwAiQA'
        'VAAbQAACIDwAAAQAIjwAABAAIG0ABCR6/oROqgAoQm0AFEzfBwdOdUjn4GAvCCIHdAAU'
        'LQACVUIkev5iTqoAKCBf0cdM3wYHTnUI+QAGAL/uAS8AEDr967AtACZnBCAfTnVIeP//'
        'Lzr+NFiXTnUAAAPy'
    ),
    'Lemmings.info': (
        '4xAAAQAAAAAAAAAAABoAEwAEAAMAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAA'
        'AAABAAAAAYAAAACAAAAAAAAAAAAAAAAAACgAAAAAAAAaABIAAgAAAAEDAAAAAAAANYAA'
        'AH/AAAD/4AABwHAAAZEwAACAIAAAAAAAAAAAAAH/8AAD//gAAf/wAAD/4AAA/+AAAP/g'
        'AAB7wAAAe8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAG7AAAB/wAAAf8AAAD+AAAH/'
        '8AAD//gAB//8AAb/7AAA/+AAAP/gAAB7wAAAe8AAAPvgAAH78AAAAAAIV0hETG9hZAAA'
        'AAAUAAAAFVNMQVZFPUxlbW1pbmdzLnNsYXZlAAAAAAhQUkVMT0FEAAAAAA8oTk9XUklU'
        'RUNBQ0hFKQAAAAAQKFdSSVRFREVMQVk9MjUpAA=='
    ),
}
# END GENERATED BY build.py


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def embedded(name: str) -> bytes:
    data = base64.b64decode(BLOBS[name])
    if not data or sha256(data) != SHA256[name]:
        raise ValueError(f'Embedded {name} is missing or damaged; run build.py')
    return data


def directory_entries(disk: bytes) -> list[tuple[str, int, int]]:
    """Return (name, offset, size) for every file in the disk directory."""
    if disk[DIRECTORY:DIRECTORY + 12] != b'Reserved\0\0\0\0':
        raise ValueError('Unexpected disk directory')
    entries = []
    offset = PAYLOAD
    for record in range(FIRST_RECORD, DIRECTORY_END, 16):
        raw = disk[record:record + 16]
        if raw == b'\xff' * 16:
            return entries
        name = raw[:12].split(b'\0', 1)[0].decode('ascii')
        if not re.fullmatch(r'[A-Za-z0-9_-]+', name):
            raise ValueError(f'Invalid file name in directory at {record:#x}')
        size = int.from_bytes(raw[12:], 'big')
        if size <= 0 or offset + size > len(disk):
            raise ValueError(f'{name}: file outside the disk')
        entries.append((name, offset, size))
        offset += size
    raise ValueError('Disk directory has no end marker')


def repack(disk: bytes, replacements: dict[str, bytes], additions: dict[str, bytes],
           limit: int) -> bytes:
    """Rewrite the directory and file area with replaced and added files."""
    entries = directory_entries(disk)
    names = [name for name, _, _ in entries]
    if replacements.keys() - set(names) or additions.keys() & set(names):
        raise ValueError('Invalid replacement or duplicate file')
    files = [(name, replacements.get(name, disk[offset:offset + size]))
             for name, offset, size in entries] + list(additions.items())
    if FIRST_RECORD + 16 * (len(files) + 1) > DIRECTORY_END:
        raise ValueError('Disk directory is full')
    end = PAYLOAD + sum(len(data) for _, data in files)
    if end > limit:
        raise ValueError(f'Files would end at {end:#x}, beyond {limit:#x}')
    result = bytearray(disk)
    result[FIRST_RECORD:DIRECTORY_END] = b'\xff' * (DIRECTORY_END - FIRST_RECORD)
    offset = PAYLOAD
    for index, (name, data) in enumerate(files):
        encoded = name.encode('ascii')
        if len(encoded) > 11 or not data:
            raise ValueError('Invalid file record')
        record = encoded + b'\0' + b'\xff' * (11 - len(encoded)) + struct.pack('>I', len(data))
        start = FIRST_RECORD + index * 16
        result[start:start + 16] = record
        result[offset:offset + len(data)] = data
        offset += len(data)
    if result[limit:] != disk[limit:] or result[:FIRST_RECORD] != disk[:FIRST_RECORD]:
        raise ValueError('Protected disk area would change')
    return bytes(result)


def jump(address: int) -> bytes:
    """JMP address.L followed by NOP: replaces exactly 8 bytes."""
    return b'\x4e\xf9' + struct.pack('>I', address) + b'\x4e\x71'


def hook(code: bytearray, address: int, original: str, replacement: bytes) -> None:
    """Replace original instructions after checking they are the expected ones."""
    expected = bytes.fromhex(original)
    start = address - CODE_BASE
    if len(expected) != len(replacement) or code[start:start + len(expected)] != expected:
        raise ValueError(f'Unexpected game code at {address:#x}')
    code[start:start + len(expected)] = replacement


def patch(disk1: bytes, disk2: bytes, variant: str = 'floppy') -> tuple[bytes, bytes]:
    """Patch the pair with the floppy or the WHDLoad ('whdload') editor."""
    symbols = VARIANTS[variant]
    bootstrap = embedded(f'{variant} bootstrap')
    editor = embedded(f'{variant} Editor')
    editor2 = embedded(f'{variant} Editor2')
    if BOOTSTRAP_BASE + len(bootstrap) > symbols['limit']:
        raise ValueError('Embedded bootstrap is too large; run build.py')
    name, offset, size = next(e for e in directory_entries(disk1) if e[0] == 'Code')
    code = bytearray(disk1[offset:offset + size])
    if CODE_BASE + len(code) != BOOTSTRAP_BASE:
        raise ValueError('Unexpected size of the game program')
    # Reserve the editor's memory when the game sets up its file cache. Load
    # Editor2 from disk 1 in place of the game's first search for disk 2
    # (BSR $3C6E / TST.W D0, 6 bytes; the bootstrap runs them afterwards and
    # returns to $510). Load Editor from disk 2 after the level metadata,
    # before the main menu starts.
    hook(code, 0x3916, 'd3f800082b4900f8', jump(symbols['reserve']))
    hook(code, 0x50A, '610037624a40', jump(symbols['load_editor2'])[:6])
    hook(code, 0x548, '610037fe61002730', jump(symbols['load_editor']))
    code.extend(bootstrap)
    return (repack(disk1, {'Code': bytes(code)}, {'Editor2': editor2}, DISK1_PAYLOAD_LIMIT),
            repack(disk2, {}, {'Editor': editor}, len(disk2)))


def identify(paths: list[Path]) -> dict[int, bytes]:
    """Read both inputs and match them to disk 1 and disk 2 by hash."""
    by_hash = {digest: number for number, digest in INPUT_SHA256.items()}
    disks: dict[int, bytes] = {}
    for path in paths:
        data = path.read_bytes()
        number = by_hash.get(sha256(data)) if len(data) == DISK_SIZE else None
        if number is None:
            raise ValueError(f'{path}: not a supported Lemmings disk image '
                             '(SHA-256 does not match)')
        if number in disks:
            raise ValueError(f'{path}: disk {number} was given twice')
        disks[number] = data
    return disks


def write(path: Path, data: bytes, inputs: list[Path]) -> None:
    if path.is_symlink():
        raise ValueError(f'{path}: refusing to write through a symbolic link')
    if path.exists() and any(path.samefile(source) for source in inputs):
        raise ValueError(f'{path}: output would overwrite an input image')
    # Write a new file and move it into place, so an existing file (or a hard
    # link to an input) is replaced rather than modified.
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, suffix='.tmp', delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(data)
        os.replace(temporary, path)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=f'Lemmings in-game level editor V{VERSION} disk patcher.')
    parser.add_argument('disks', nargs=2, type=Path, metavar='DISK.adf',
                        help='the two original Lemmings disk images, in any order')
    parser.add_argument('-o', '--output', type=Path, default=Path('.'),
                        help='directory for the patched images (default: current directory)')
    parser.add_argument('--whdload', type=Path, metavar='INSTALL_DIR',
                        help='write the WHDLoad install to this directory instead')
    args = parser.parse_args()
    try:
        disks = identify(args.disks)
        if args.whdload:
            disk1, disk2 = patch(disks[1], disks[2], 'whdload')
            output = args.whdload
            files = {'Lemmings.slave': embedded('Lemmings.slave'), 'Disk.1': disk1,
                     'Disk.2': disk2, 'Lemmings.info': embedded('Lemmings.info')}
        else:
            output = args.output
            files = dict(zip(OUTPUT_NAMES.values(), patch(disks[1], disks[2])))
        output.mkdir(parents=True, exist_ok=True)
        for name, data in files.items():
            path = output / name
            write(path, data, args.disks)
            print(f'{path}  SHA-256 {sha256(data)}')
    except (OSError, ValueError) as error:
        parser.exit(1, f'error: {error}\n')


if __name__ == '__main__':
    main()
